### ISSUE TITLE
WAF policy assigned to all HostGroup VS resources

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2583] opened 2022-09-13 07:31 UTC
#### Setup Details
 CIS Version : 2.10     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/      
 Orchestration: K8S

#### Description  
Customer is deploying multiple VS under the same hostGroup and enables only of 1 VS resource a WAF policy through policyCRD, then all VirtualServers are assigned WAF policies
 
#### Steps To Reproduce
1) Create policyCRD 
```
apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: waf-policy
spec:
  l7Policies:
    waf: /Common/basic_waf_policy
  profiles:
    logProfiles:
      - /Common/Log all requests
```
2) Create VS with only the `app1-vs` VS mentioning the  `policyName: waf-policy`
```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: app1-vs
  labels:
    f5cr: "true"
spec:
  hostGroup: "test123"
  host: "*.f5demo.test"
  ipamLabel: "prod"
  virtualServerName: "apps-vs"
  pools:
  - path: /
    service: app1-svc
    servicePort: 8080
---

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: tea-vs
  labels:
    f5cr: "true"
spec:
  hostGroup: "test123"
  host: "tea.f5demo.test"
  ipamLabel: "prod"
  virtualServerName: "apps-vs"
  pools:
  - path: /
    service: tea-svc
    servicePort: 8080

---

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: app2-vs
  labels:
    f5cr: "true"
spec:
  hostGroup: "test123"
  host: "www.f5demo.test"
  ipamLabel: "prod"
  policyName: waf-policy
  virtualServerName: "apps-vs"
  pools:
  - path: /
    service: app2-svc
    servicePort: 8080

```
3) you will see that all VS have attached the WAF policy.

#### Expected Result 
The expected result is that all VS that dont have WAF policy declared, should have ASM disabled (on the policy) and the only that have WAF policy declared, should have ASM enable with the correct WAF name (specified on the policy)

**Comment by trinaths** [comment] 2022-09-16 15:05
Created [CONTCNTR-3597] for internal tracking.

**Comment by subbuv26** [comment] 2022-09-22 19:38
Hi @skenderidis, this behaviour is intended to work this way itself, by design. As multiple VirtualServers would be clubbed into one group, we have flexibility to specify per group specification just in one of the VirtualServers, to avoid the duplication of per group specs such as policyName, hostGroup, etc

In your case, it can be suggested to create two groups one with WAF another without WAF.

**Comment by trinaths** [comment] 2022-12-01 08:44
Closing this issue. Please follow the PE recommendation.

**Closed by trinaths** 2022-12-01 08:44 UTC
Labels: bug, jira
