### ISSUE TITLE
When updating routes, old service pools are not removed until after a refresh cycle

### ISSUE THREAD

**Issue by russokj** [F5Networks/k8s-bigip-ctlr#471] opened 2018-01-05 17:28 UTC
#### Description
In Openshift, if a route changes which service it is using (for instance, upgrading to a new version), the pool for the old service it left configured on the BIG-IP until the next refresh cycle.  To test, configure two services in openshift: svc-v1 & svc-v2. Then configure a route to use svc-v1. When the route is changed to use svc-v2, the BIG-IP will show the pools for both svc-v1 and svc-v2 until either the next refresh cycle of the controller, or the user deletes the service svc-v1.

#### Kubernetes Version
Openshift v1.4.1

#### Controller Version
master as of 1/3/18

#### BIG-IP Version
BIG-IP 12.1.0 Build 1.0.1447 Hotfix HF1

#### Diagnostic Information
The following was the initial route definition before switch the service to svc-v2:
```
apiVersion: v1
kind: Route
metadata:
  name: foo-com
  namespace: default
spec:
  host: foo.com
  path: /foo
  to:
    kind: Service
    name: svc-v1
```

**Comment by sjberman** [comment] 2018-01-08 16:21
The root cause of this is that when a Route changes its Service, we see an update for that Route and grab the new Service off of the Route and move forward with processing. We don't have any information at that point about the previous Service that the Route pointed to, as the Route no longer contains that information, so we don't initially clean up the previous pool.

A potential fix for this is every time we process some update, we loop through all resources (ConfigMaps, Ingresses, Routes) and loop through all pools in our currently stored configs, and if any pools point to a Service that isn't in any of our resources, we delete those pools. This is expensive, though.

**Closed** 2018-01-29 16:52 UTC
Labels: P3, bug
