### ISSUE TITLE
urgent - Controller fails all the time

### ISSUE THREAD

**Issue by wheestermanstoyota** [F5Networks/k8s-bigip-ctlr#1082] opened 2019-11-12 14:32 UTC
#### Description
Controler is failing all the time inside my k8s cluster

#### Kubernetes Version

Docker-EE 3.0

Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-docker-1", GitCommit:"51f07ed581173b287557a03fea5e3a0d14093729", GitTreeState:"clean", BuildDate:"2019-09-19T18:37:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

#### Controller Version
1.11.0, same for 1.10.0

#### Diagnostic Information

2019/11/12 14:23:18 [WARNING] Overwriting existing entry for backend {ServiceName:kong-ee-tme-dev-kong-portal ServicePort:8446 Namespace:tme-ns-kong-dev}
2019/11/12 14:23:19 [WARNING] Overwriting existing entry for backend {ServiceName:kong-ee-tme-dev-kong-portal ServicePort:8446 Namespace:tme-ns-kong-dev}
2019/11/12 14:23:19 [WARNING] Overwriting existing entry for backend {ServiceName:kong-ee-tme-dev-kong-admin ServicePort:8444 Namespace:tme-ns-kong-dev}
2019/11/12 14:23:24 [WARNING] Overwriting existing entry for backend {ServiceName:tme-svc-http-tme-log-viewer ServicePort:8080 Namespace:tme-ns-http-dev}
2019/11/12 14:23:24 [WARNING] Overwriting existing entry for backend {ServiceName:tme-svc-http-tme-log-viewer ServicePort:8080 Namespace:tme-ns-http-dev}
2019/11/12 14:23:24 [WARNING] Overwriting existing entry for backend {ServiceName:tme-svc-http-cwsweb-ui ServicePort:8080 Namespace:tme-ns-http-dev}
E1112 14:23:27.880004       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:2031
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:1331
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:1016
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:938
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:873
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:813
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/usr/local/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11b5b4e]

goroutine 212 [running]:
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x19e18e0, 0x2f748a0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).setIngressStatus(0xc000234000, 0xc000a30580, 0xc000afc9c0)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:2031 +0x3e
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).syncIngresses(0xc000234000, 0xc000a7d9d0, 0xc0001f6f20, 0x11, 0xc0001f6e80, 0x1a, 0x0, 0x0, 0x0, 0x0, ...)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:1331 +0x102a
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).syncVirtualServer(0xc000234000, 0xc0001f6f20, 0x11, 0xc0001f6e80, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:1016 +0x9a0
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).processNextVirtualServer(0xc000234000, 0xc000944500)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:938 +0x458
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).virtualServerWorker(0xc000234000)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:873 +0x2b
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).virtualServerWorker-fm()
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:813 +0x2a
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00043fe10)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96 +0x54
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00043fe10, 0x3b9aca00, 0x0, 0x101, 0xc000256540)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0xa2
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00043fe10, 0x3b9aca00, 0xc000256540)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
created by github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).runImpl
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:813 +0x13d

**Comment by ssurenr** [comment] 2019-11-12 14:43
@wheestermanstoyota Could you please create an SR with your configuration.

**Comment by wheestermans31** [comment] 2019-11-12 15:23
The problem was caused by deployment issue

    virtual-server.f5.com/http-port: ""
    virtual-server.f5.com/ip: ""
    virtual-server.f5.com/partition: ""

These three values were empty, causing the controller to fail. something to be fixed.

**Comment by trinaths** [comment] 2019-11-15 11:34
@wheestermanstoyota - You must either give the "default-ingress-ip [1]" configuration option in bigip-controller deployment or give "virtual-server.f5.com/ip: <IP-address> [2]" for the ingress to work. Giving either of the options, the controller won't crash. 

Not using the annotations, virtual-server.f5.com/http-port or virtual-server.f5.com/partition doesn't crash the big-ip controller.

[1] https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.11/#kubernetes
[2] https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.11/#supported-ingress-annotations

**Comment by wheestermanstoyota** [comment] 2019-11-15 11:49
I understand, but best is to check if all are fine and report more friendly in the logs, instead of just crashing the controller.

**Comment by trinaths** [comment] 2019-11-15 12:06
> I understand, but best is to check if all are fine and report more friendly in the logs, instead of just crashing the controller.

We are tracking this issue and working on the fix.

**Comment by mdditt2000** [comment] 2019-12-10 23:16
@trinaths i dont see a Jira for this fix. Still planning milestone of 1.12 or 1.13?

**Comment by trinaths** [comment] 2019-12-11 06:22
@mdditt2000 : We fixed this with 1.12 - Ingress with AS3. If both annotation and controller deployment options are not given, we throwing an error in the log. No crash of the controller.
Closing this issue.

**Closed by trinaths** 2019-12-11 06:22 UTC
Labels: bug, customer-found
