### ISSUE TITLE
K8s unexpected across namespace monitor (AS3)

### ISSUE THREAD

**Issue by liaojianxiong** [F5Networks/k8s-bigip-ctlr#1185] opened 2020-02-20 03:36 UTC
#### Description
I deployed two ingresses with configmap into two namespaces, and then I deployed two CIS to monitor the two namespaces separately, it works well. one cis watch one namespace.

But when I deploy another ingress with configmap+AS3 in the third namespace, and no CIS was configured to watch the third namespace. The two CIS both watch the AS3 deployment and configure the LTM, it is an unexceptional behavior.

Maybe it is a bug, pls check!

Kubernetes Version
v1.9.0

Controller Version
v1.12

BIG-IP Version
v13.1.1.5

**Comment by wangzheng** [comment] 2020-02-27 18:51
This shall be a duplicated report with #1145 . The problem is that the appManager for AS3 will use the built-in "NamespaceAll" as the "namespace" parameter when initializing the AS3 Informers:

K8s-bigip-ctlr/pkg/appmanager/as3Manager.go

534     func (appMgr *Manager) SetupAS3Informers() error {
535        // resyncPeriod is zero to avoid repolling
536        var resyncPeriod time.Duration
537        // namespace is Empty to create watchers for all namespaces
538        namespace := v1.NamespaceAll          <<<<<=====

Not sure if this is by design or not. In most cases, we want the controller only monitor the namespace(s) they need to maintain precise granularity, that's make sense.

**Comment by wangzheng** [comment] 2020-02-28 11:59
Maybe this can workaround the issue (I don't tested, just a pseudo-fix):

func (appMgr *Manager) checkValidAS3ConfigMap(obj interface{}) (
	bool, []*serviceQueueKey) {

	var keyList []*serviceQueueKey
	cm := obj.(*v1.ConfigMap)
	namespace := cm.ObjectMeta.Namespace

	log.Debugf("[AS3] Found AS3 ConfigMap - %s.", cm.ObjectMeta.Name)
	
+	ownedCfgmap := false
+	for _, ns := range appMgr.GetAllWatchedNamespaces() {
+		if ns == namespace {
+			ownedCfgmap = true
+		}
+	}
+	
+	if ownedCfgmap == false {
+		log.Debugf("[AS3] AS3 ConfigMap %s is in a different namespace %s, skipping.", cm.ObjectMeta.Name, namespace)
+		return false, keyList
+	}
	
	key := &serviceQueueKey{
		Namespace: namespace,
		AS3Name:   cm.ObjectMeta.Name,
		AS3Data:   cm.Data["template"],
	}
	keyList = append(keyList, key)
	return true, keyList
}

**Comment by mdditt2000** [comment] 2020-05-12 16:58
CONTCNTR-1693 - Internal Jira. Completed the regression. Resolved in CIS 2.0 coming next week.

**Closed by mdditt2000** 2020-05-12 16:58 UTC
Labels: P1, bug, customer-found
