### ISSUE TITLE
Provide "debug" output on AS3 declaration failure

### ISSUE THREAD

**Issue by walterk82** [F5Networks/k8s-bigip-ctlr#1881] opened 2021-06-28 14:33 UTC
#### Title
Provide "debug" output on AS3 declaration failure

#### Description
In the current deployment model, if an AS3 post fails with a 422 or similar response code, the only response given is the error from AS3 itself.  However, AS3 doesn't do a good job of logging what part of the declaration is causing the conflict.  i.e. there is no contextual data of where there error is occurring.  This is probably fine when you have direct control over the AS3 post.  However, when running under CIS the end-user is not building the AS3 directly so this contextual information is lost.

#### Actual Problem
CIS does not provide enough context for errors that are reported via AS3 post.

#### Solution Proposed
Update CIS to post AS3 with the `traceResponse: true` flag so that AS3 detailed information is always available.  Then if AS3 encounters any error 422/500 etc...  Log the value for of the AS3 response along with the error message to CIS logs.  This will allow operations teams to review the AS3 declaration causing the issue to find the namespace/pod that has an incorrect configuration, without enabling global debug mode for CIS.

#### Alternatives
The only option currently available is to enable global debug mode for CIS which is very verbose during normal operation.

**Comment by trinaths** [comment] 2021-06-30 20:47
Configure CIS with `--log-as3-response=true` which will help you find the detailed error log. Please share your finding enable this deployment option.

**Comment by walterk82** [comment] 2021-06-30 20:51
Ideally, I was thinking an option such as `--log-as3-response=onerror` so that the logs were output more judiciously.

**Comment by walterk82** [comment] 2021-06-30 20:55
Also, does `--log-as3-response=true` force the AS3 option to `traceResponse=true`

**Comment by trinaths** [comment] 2021-07-01 09:24
@walterk82 ```--log-as3-response``` logs the AS3 response if there are 422 or other errors. This helps in debugging with errors found in AS3 declaration. 

Sample error log :

```
[ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/hubModeclassic/A2/a1_80_vs_n2/virtualAddresses/0: should match format "f5ip"] message:declaration is invalid]
```

**Comment by trinaths** [comment] 2021-09-07 18:43
Hope the issue is resolved. closing this issue. Please reopen with further findings.

**Closed by trinaths** 2021-09-07 18:43 UTC
Labels: feature-request, awaiting response
