### ISSUE TITLE
Long live connection being disrupted as CIS deleting arp/fdb 

### ISSUE THREAD

**Issue by myf5** [F5Networks/k8s-bigip-ctlr#1973] opened 2021-08-25 04:15 UTC
#### Setup Details
 CIS Version : 2.4     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.25      
 Agent Mode: CCCL       
 Orchestration: K8S   
 Orchestration Version:  1.18
 Pool Mode: Cluster 
 Additional Setup details:  flannel vxlan mode

#### Description  
When `kubectl delete` is executed, the k8s  endpoint controller will find the change from the API.  
At this time,  CIS also watched the change and delete the pool member and the related ARP/FDB.  While  the customer's container was not deleted at the time. 
The bigip will keep the long live active connection, this is expected, but as ARP/FDB was deleted, this cause underneath packet transit failure.  This cause long live connection got disruption, and cause not expect business result.

#### Steps To Reproduce
See below picture:

![](https://myf5.net/upload/2021/08/cis-delete-arp-early.png)

#### Expected Result 
CIS do not delete ARP/FDB before the container lifecycle finish.

#### Actual Result  
CIS delete ARP/FDB early.

#### Diagnostic Information:
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by trinaths** [comment] 2021-09-07 09:59
@myf5 - Since pool member is deleted, CIS triggers removal of FDB/ARP entires and is an expected behaviour and since the pod is deleted there is no meaning in maintaining the connection active. What is main purpose you are looking regarding this issue ?

**Comment by myf5** [comment] 2021-09-12 04:22
look at the page, the pod actually is not deleted when CIS removing FDB/ARP. This cause connection disconnected.

**Comment by trinaths** [comment] 2021-09-15 06:27
CIS relies on kube api with its informers and listens for events to care about the resources its monitoring. So we need to find the api calls where CIS using informers can get the event where it can act to remove the arp entries when pod is deleted. Also we need to make sure informers are capable to track these events in k8s cluster. please share the event logs when these events are being triggered to know more about the logs. This helps to know how can we use informers in CIS to know the events and act accordingly.

**Comment by myf5** [comment] 2021-09-15 07:14
Let app container does not quit application immediately when get sigterm signal, to make sure all exist connections to be handled probably.   Every thing is follow normal k8s events.  Not sure, what kind of events you want get.
Please advice the steps how to collect the events. Thanks

**Comment by myf5** [comment] 2021-09-15 07:17
Let app container does not quit application immediately when get sigterm signal, to make sure all exist connections to be handled probably.   Every thing is follow normal k8s events.  Not sure, what kind of events you want get.
Please advice the steps how to collect the events. Thanks

**Comment by trinaths** [comment] 2021-09-15 08:07
you can use `Kubectl get events`. more info on event logging - https://kubernetes.io/docs/tasks/debug-application-cluster/

**Comment by myf5** [comment] 2021-09-16 09:40
Vicent Li thought consider let flannel to support dynamic arp for flannel vxlan,  he created an idea at flannel repo for propose #https://github.com/flannel-io/flannel/issues/1478

before flannel taking action, still need find a way to fix from CIS .

**Comment by vincentmli** [comment] 2021-09-16 14:27
@trinaths I agree the event timing can be always tricky to get it right.  let's see if there is good workaround, if customer use AS3, can they re-deploy the AS3 with specific pool member marked offline, and CIS take that AS3 re-declaration and send it to BIG-IP through some sort of "patch" method to mark the pool member offline on BIG-IP?

**Comment by vincentmli** [comment] 2021-09-16 14:33
@myf5 in regard to K8S API request tracing, I learned through https://github.com/cilium/cilium/issues/17192#issuecomment-912171624 that you can trace each K8S API request and timing though auditing, not sure if it is possible with customer, but that will give you an idea for each request and response and timing, though I am not very familiar with K8S API myself.

**Comment by trinaths** [comment] 2021-09-17 05:24
> @trinaths I agree the event timing can be always tricky to get it right. let's see if there is good workaround, if customer use AS3, can they re-deploy the AS3 with specific pool member marked offline, and CIS take that AS3 re-declaration and send it to BIG-IP through some sort of "patch" method to mark the pool member offline on BIG-IP?

We don't support "patch" method with CIS.

**Comment by trinaths** [comment] 2021-09-17 05:25
> @myf5 in regard to K8S API request tracing, I learned through [cilium/cilium#17192 (comment)](https://github.com/cilium/cilium/issues/17192#issuecomment-912171624) that you can trace each K8S API request and timing though auditing, not sure if it is possible with customer, but that will give you an idea for each request and response and timing, though I am not very familiar with K8S API myself.

Enabling audit requires changes kube-api-server YAML. So check with the end user whether is possible in their environment.

**Comment by trinaths** [comment] 2021-09-17 08:39
Created CONTCNTR-2925 for internal tracking.

**Comment by myf5** [comment] 2021-09-18 01:11
> Created CONTCNTR-2925 for internal tracking.

Agree. Dont think we need request customer to enable API audit. The issue should be investigate internally first. PD side can create a sample app which dont respond sigterm signal to simulate the customer app behavior and to see what workaround/fix can be take.

when CIS found some ep removed, then CIS know which k8s svc and bigip pool member will be affected. 
CIS keep this info for sometime in memory or keep as temp static.
CIS force offline the members.
CIS check if the pod is really being deleted.
if yes, delete the member and arp
if no, keep the status. 
This need loop checking, from performance point, may not be good idea.

**Comment by trinaths** [comment] 2021-11-11 06:45
When a pod is deleted, k8s sends SIGTERM signal to the pod and gives a grace period for the pod to shutdown (terminationGracePeriodSeconds ~ default 30 seconds) and sends a SIGKILL signal to terminate completely. 

When SIGTERM signal is sent to pod, at the same time, corresponding kube-proxy, iptables, coreDNS are also signalled. This is the same time, when k8s informer also gets events. 

However, the purpose of grace period is to ensure smooth termination of existing requests, but not to accept new requests. Replication controller will take action and create new pod meantime (based on number of replicas mentioned in deployment spec).

Some notes : 

Monitor configured in BIGIP can be adjusted to poll for shorter times - 2 seconds interval and timeout of 4 seconds. Also, readiness probes can be part of deployment options as well, for k8s to handle number of replicas correctly. 
If controller adds a delay in processing the deletion, still there is no guarantee that k8s iptables maintains the route to the pod, even in that case, traffic will be stopped flowing.
Permalink

`investigate this issue - Can CIS watch events where ARP/FDB are deleted when POD is terminated completely? or can we wait for 30sec to remove ARP/FDB entries when we get a Delete event - this hits performance for sure. Will this hit CIS design and the way resources are being processed ? (IMO, yes).` 

> terminationGracePeriodSeconds - depends on customer environment configuration. It can be as long as 10 mins for intense processing applications (Eg: video streaming services). CIS has no access to this deployment parameters.

Customers can deploy in NodePort mode to avoid this scenario.
Events happen in ms duration - so if interested, health monitor can be configured with shorter intervals.

Closing this issue.

**Closed by trinaths** 2021-11-11 06:45 UTC
Labels: enhancement, jira
