### ISSUE TITLE
_AS3 partition not removed when using custom-resource-mode=true

### ISSUE THREAD

**Issue by sbarre-esit** [F5Networks/k8s-bigip-ctlr#1442] opened 2020-08-04 19:36 UTC
#### Setup Details
 CIS Version : 2.1.0
 Build: f5networks/k8s-bigip-ctlr:2.1.0
 BIGIP Version: BIG-IP 14.1.2.6 Build 0.0.2 Point Release 6
 AS3 Version: f5-appsvcs-3.20.0-3.noarch
 Agent Mode: AS3
 Orchestration: OSCP
 Orchestration Version: v4.4
 Pool Mode: Cluster

#### Description  
The 2.1 release notes https://clouddocs.f5.com/containers/latest/reference/release-notes.html say that the _AS3 partition will be removed but it is still there after upgrading.

#### Steps To Reproduce
1) Upgrade from CIS 2.0 to 2.1
2) Check list of partition in F5 BIG-IP web console

#### Expected Result 
openshift_AS3 partition removed

#### Actual Result  
openshift_AS3 partition still exists

#### Diagnostic Information
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-bigip-01
  namespace: f5-bigip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-bigip-ctlr
      name: k8s-bigip-ctlr
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - k8s-bigip-ctlr
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=1.2.3.4
        - --bigip-partition=openshift
        - --pool-member-type=cluster
        - --openshift-sdn-name=/Common/openshift_vxlan
        - --manage-routes=false
        - --manage-configmaps=false
        - --custom-resource-mode=true
        - --insecure=true
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: bigip-login
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bigip-login
        image: f5networks/k8s-bigip-ctlr:2.1.0
        imagePullPolicy: IfNotPresent
        name: k8s-bigip-ctlr
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr
      terminationGracePeriodSeconds: 30
```  

```
2020/08/04 19:34:04 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.1.0, BuildInfo: cloud-user-f76af0a-20200728071700
2020/08/04 19:34:04 [INFO] ConfigWriter started: 0xc0004c08a0
2020/08/04 19:34:04 [INFO] Started config driver sub-process at pid: 18
2020/08/04 19:34:04 [INFO] [CORE] NodePoller (0xc0005de360) registering new listener: 0x11e3820
2020/08/04 19:34:04 [INFO] [CORE] NodePoller (0xc0005de360) registering new listener: 0x11e3890
2020/08/04 19:34:04 [INFO] Starting Custom Resource Manager
2020/08/04 19:34:04 [INFO] Starting VirtualServer Informer
2020/08/04 19:34:04 [INFO] Starting TLSProfile Informer
2020/08/04 19:34:04 [INFO] Enqueueing VirtualServer: &{{VirtualServer cis.f5.com/v1} {my-new-virtual-server  steve-test /apis/cis.f5.com/v1/namespaces/steve-test/virtualservers/my-new-virtual-server bdabcd7a-685d-40de-a508-292b1cb3e0a5 14828089 2 2020-08-04 17:33:25 +0000 UTC <nil> <nil> map[f5cr:true] map[] [] []  []} {cafe.example.com 1.2.3.5 [{/ django-psql-example 8080  {http /  5 10}}]  }}
2020/08/04 19:34:04 [INFO] [CORE] NodePoller started: (0xc0005de360)
2020/08/04 19:34:08 [INFO] [2020-08-04 19:34:08,524 __main__ INFO] entering inotify loop to watch /tmp/k8s-bigip-ctlr.config172079117/config.json
```

**Comment by cisbotctlr** [comment] 2020-08-04 19:36
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment] 2020-08-04 20:01
Recreating in my environment using CRDs.

**Comment by mdditt2000** [comment] 2020-08-04 21:49
@sbarre-esit i cannot reproduce this.

Tried using CIS 2.0 where i can see _AS3 getting created only for TEEMS data "phone phone"

Upgraded to CIS 2.1 and _AS3 is removed correctly

2020/08/04 21:26:01 [INFO] [AS3] Initializing AS3 Agent
2020/08/04 21:26:01 [DEBUG] [AS3] No certs appended, using only system certs
2020/08/04 21:26:01 [DEBUG] [AS3] Validating AS3 schema with  as3-schema-3.20.0-3-cis.json
2020/08/04 21:26:01 [DEBUG] [AS3] posting GET BIGIP AS3 Version request on https://192.168.200.92/mgmt/shared/appsvcs/info
2020/08/04 21:26:01 [DEBUG] [AS3] BIGIP is serving with AS3 version: 3.20.0
**2020/08/04 21:26:01 [DEBUG] [AS3] Removing Partition k8s_AS3**
2020/08/04 21:26:01 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/08/04 21:26:05 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s_AS3 --- message: success
2020/08/04 21:26:35 [DEBUG] [AS3] Posting AS3 Declaration
2020/08/04 21:26:35 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/08/04 21:26:37 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s --- message: no change
2020/08/04 21:26:37 [DEBUG] [AS3] Preparing response message to response handler
2020/08/04 21:26:37 [DEBUG] [AS3] AppManager wrote endpoints to VxlanMgr
2020/08/04 21:26:37 [DEBUG] [AS3] Sent response message to response handler

Let me try a configuration where an old route or Ingress was left on BIG-IP with CIS.

**Comment by agupta49** [comment] 2020-08-05 15:13
@sbarre-esit For custom-resource-mode=true CIS will not delete _AS3 partition. We need to clean/remove the _AS3 partition manually. CIS removes _AS3 partition with agent as3 or cccl.

**Comment by mdditt2000** [comment] 2020-08-05 16:10
@agupta49 that does make sense and i am seeing the same thing.

@sbarre-esit to resolve this issue please try the following:

**Step 1:** Remove the following from your CIS arguments
```
 - --manage-routes=false
 - --manage-configmaps=false
 - --custom-resource-mode=true
```
**Step 2:** Delete/Create the CIS deployment. You will see the following

2020/08/05 16:02:35 [INFO] [AS3] Initializing AS3 Agent
2020/08/05 16:02:35 [DEBUG] [AS3] No certs appended, using only system certs
2020/08/05 16:02:35 [DEBUG] [AS3] Validating AS3 schema with  as3-schema-3.20.0-3-cis.json
2020/08/05 16:02:35 [DEBUG] [AS3] posting GET BIGIP AS3 Version request on https://192.168.200.92/mgmt/shared/appsvcs/info
**2020/08/05 16:02:35 [DEBUG] [AS3] BIGIP is serving with AS3 version: 3.20.0
2020/08/05 16:02:35 [DEBUG] [AS3] Removing Partition k8s_AS3**
2020/08/05 16:02:35 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/08/05 16:02:38 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s_AS3 --- message: success

2020/08/05 16:03:08 [DEBUG] [AS3] Posting AS3 Declaration
2020/08/05 16:03:08 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/08/05 16:03:10 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s --- message: no change
2020/08/05 16:03:10 [DEBUG] [AS3] Preparing response message to response handler
2020/08/05 16:03:10 [DEBUG] [AS3] AppManager wrote endpoints to VxlanMgr
2020/08/05 16:03:10 [DEBUG] [AS3] Sent response message to response handler

**Step 3:** 

Re-add - --custom-resource-mode=true

Note: You only need - --custom-resource-mode=true. Once CRD mode=true CIS will ignore routes/ingress/configmaps. 

Thanks Mark

**Comment by sbarre-esit** [comment] 2020-08-05 23:52
@mdditt2000 thanks, the steps worked and removed the partition.

**Comment by mdditt2000** [comment] 2020-08-06 06:15
Closing issue - Resolved.

**Closed by mdditt2000** 2020-08-06 06:15 UTC
Labels: crd, documentation, ready to close
