### ISSUE TITLE
Too many 503 errors that we should pay attention to.

### ISSUE THREAD

**Issue by zongzw** [F5Networks/k8s-bigip-ctlr#2192] opened 2022-01-20 05:11 UTC
#### Setup Details
 CIS Version : 2.6.1 or master branch, they can both reproduce.
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: BIG-IP 15.1.4 Build 0.0.47 Final 
 AS3 Version: 3.31.0
 Agent Mode: AS3
 Orchestration: K8S
 Orchestration Version:       
 Pool Mode: Cluster
 Additional Setup details: 

#### Description  

There are so many 503 errors saying: `There is an active asynchronous task executing`
Several issues #1391  #1137 #1730 #1291,  are related to or mentioned this issue, they are all closed state.

```
2021/12/26 02:48:53 [INFO] Traceback (most recent call last):
2021/12/26 02:48:53 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 352, in _do_reset
2021/12/26 02:48:53 [INFO]     incomplete = self._update_cccl(config)
2021/12/26 02:48:53 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 479, in _update_cccl
2021/12/26 02:48:53 [INFO]     incomplete += mgr._apply_net_config(cfg_net)
2021/12/26 02:48:53 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 136, in _apply_net_config
2021/12/26 02:48:53 [INFO]     return self._cccl.apply_net_config(config)
2021/12/26 02:48:53 [INFO]   File "/app/src/f5-cccl/f5_cccl/api.py", line 102, in apply_net_config
2021/12/26 02:48:53 [INFO]     return self._service_manager.apply_net_config(services)
2021/12/26 02:48:53 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 707, in apply_net_config
2021/12/26 02:48:53 [INFO]     retval = self._service_deployer.deploy_net(desired_config)
2021/12/26 02:48:53 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 471, in deploy_net
2021/12/26 02:48:53 [INFO]     self._bigip.refresh_net()
2021/12/26 02:48:53 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 146, in refresh_net
2021/12/26 02:48:53 [INFO]     self._refresh_net()
2021/12/26 02:48:53 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 416, in _refresh_net
2021/12/26 02:48:53 [INFO]     for record in tunnel.records_s.get_collection():
2021/12/26 02:48:53 [INFO]   File "/usr/local/lib/python3.6/site-packages/f5/bigip/resource.py", line 800, in get_collection
2021/12/26 02:48:53 [INFO]     self.refresh(**kwargs)
2021/12/26 02:48:53 [INFO]   File "/usr/local/lib/python3.6/site-packages/f5/bigip/resource.py", line 651, in refresh
2021/12/26 02:48:53 [INFO]     self._refresh(**kwargs)
2021/12/26 02:48:53 [INFO]   File "/usr/local/lib/python3.6/site-packages/f5/bigip/resource.py", line 634, in _refresh
2021/12/26 02:48:53 [ERROR] [2021-12-26 02:48:53,019 __main__ ERROR] Unexpected error
2021/12/26 02:48:53 [INFO]     response = refresh_session.get(uri, **requests_params)
2021/12/26 02:48:53 [INFO]   File "/usr/local/lib/python3.6/site-packages/icontrol/session.py", line 295, in wrapper
2021/12/26 02:48:53 [INFO]     raise iControlUnexpectedHTTPError(error_message, response=response)
2021/12/26 02:48:53 [INFO] icontrol.exceptions.iControlUnexpectedHTTPError: 503 Unexpected Error: Service Unavailable for uri: https://10.250.87.7:8443/mgmt/tm/net/fdb/tunnel/~Common~fl-tunnel/records/
2021/12/26 02:48:53 [INFO] Text: '{"code":503,"message":"There is an active asynchronous task executing.","errorStack":[],"apiError":32964609}'
2021/12/26 02:48:53 [ERROR] [2021-12-26 02:48:53,021 __main__ ERROR] Error applying config, will try again in 1 seconds
```

#### Steps To Reproduce
1) Run CIS with as3 mode
2) See logs

**Comment by trinaths** [comment] 2022-01-20 18:10
> 503 Unexpected Error: Service Unavailable for uri: https://10.250.87.7:8443/mgmt/tm/net/fdb/tunnel/~Common~fl-tunnel/records/

These are CCCL agent level issues when service is busy or cannot handle the request properly at the other end.  

> [ERROR] [2021-12-26 02:48:53,021 __main__ ERROR] Error applying config, will try again in 1 seconds

Upon this error, a retry will happen to post the data to BIGIP.

This issue seems not a bug but an expected behaviour to report the agent side transaction status.

Closing this issue.

**Closed by trinaths** 2022-01-20 18:10 UTC
Labels: bug, untriaged

**Comment by zongzw** [comment] 2022-01-20 18:21
If it is an expected behavior, how about to simplify the error log, limit it to 1 single log instead of 30 lines.
Repeat them hundreds / thousands / millions times in the logs is meaningless, given no valuable info.

**Comment by trinaths** [comment] 2022-01-21 06:11
@zongzw  Agree, from UX view. But this is an Error log which precede configured log levels.
