### ISSUE TITLE
Too many info log output

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2293] opened 2022-03-15 15:45 UTC
In CIS 2.7.1, each time a namespace create or delete, a service create or delete there are lot's of INFO log output as below, seems these kinds of log should be DEBUG level.

~~~
2022/03/15 13:53:24 [INFO] No VirtualServers founds in namespace app-l7
2022/03/15 13:53:24 [INFO] No VirtualServers for TransportServer founds in namespace app-l7
2022/03/15 13:53:24 [INFO] No IngressLink founds in namespace app-l7
2022/03/15 13:53:24 [INFO] Service app-l7/coffee-svc doesn't exist
2022/03/15 13:53:24 [INFO] No VirtualServers founds in namespace app-l7
2022/03/15 13:53:24 [INFO] No VirtualServers for TransportServer founds in namespace app-l7
2022/03/15 13:53:24 [INFO] No IngressLink founds in namespace app-l7
2022/03/15 13:53:24 [INFO] Service app-l7/tea-svc doesn't exist
2022/03/15 13:53:41 [INFO] Enqueueing Namespace: &Namespace{ObjectMeta:{app-l7   /api/v1/namespaces/app-l7 12868cef-9a65-481d-94c9-13c1453cb7be 66063 0 2022-03-15 14:27:26 +0000 UTC 2022-03-15 14:29:18 +0000 UTC <nil> map[cis_scanner_zone:zone_1] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"cis_scanner_zone":"zone_1"},"name":"app-l7"}}
] [] []  [{kubectl Update v1 2022-03-15 14:27:26 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:cis_scanner_zone":{}}},"f:status":{"f:phase":{}}}} {kube-controller-manager Update v1 2022-03-15 14:29:25 +0000 UTC FieldsV1 {"f:status":{"f:conditions":{".":{},"k:{\"type\":\"NamespaceContentRemaining\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"NamespaceDeletionContentFailure\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"NamespaceDeletionDiscoveryFailure\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"NamespaceDeletionGroupVersionParsingFailure\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"NamespaceFinalizersRemaining\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}}}}}]},Spec:NamespaceSpec{Finalizers:[kubernetes],},Status:NamespaceStatus{Phase:Terminating,Conditions:[]NamespaceCondition{NamespaceCondition{Type:NamespaceDeletionDiscoveryFailure,Status:False,LastTransitionTime:2022-03-15 14:29:25 +0000 UTC,Reason:ResourcesDiscovered,Message:All resources successfully discovered,},NamespaceCondition{Type:NamespaceDeletionGroupVersionParsingFailure,Status:False,LastTransitionTime:2022-03-15 14:29:25 +0000 UTC,Reason:ParsedGroupVersions,Message:All legacy kube types successfully parsed,},NamespaceCondition{Type:NamespaceDeletionContentFailure,Status:False,LastTransitionTime:2022-03-15 14:29:25 +0000 UTC,Reason:ContentDeleted,Message:All content successfully deleted, may be waiting on finalization,},NamespaceCondition{Type:NamespaceContentRemaining,Status:False,LastTransitionTime:2022-03-15 14:29:35 +0000 UTC,Reason:ContentRemoved,Message:All content successfully removed,},NamespaceCondition{Type:NamespaceFinalizersRemaining,Status:False,LastTransitionTime:2022-03-15 14:29:25 +0000 UTC,Reason:ContentHasNoFinalizers,Message:All content-preserving finalizers finished,},},},} on Delete

2022/03/15 13:56:15 [INFO] Enqueueing Namespace: &Namespace{ObjectMeta:{app-l7   /api/v1/namespaces/app-l7 f695bfd4-6427-4bae-8d54-08f2bc05aa65 66425 0 2022-03-15 14:32:09 +0000 UTC <nil> <nil> map[cis_scanner_zone:zone_1] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"cis_scanner_zone":"zone_1"},"name":"app-l7"}}
] [] []  [{kubectl Update v1 2022-03-15 14:32:09 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:cis_scanner_zone":{}}},"f:status":{"f:phase":{}}}}]},Spec:NamespaceSpec{Finalizers:[kubernetes],},Status:NamespaceStatus{Phase:Active,Conditions:[]NamespaceCondition{},},}
2022/03/15 13:56:15 [INFO] Starting VirtualServer Informer
2022/03/15 13:56:15 [INFO] Starting TLSProfile Informer
2022/03/15 13:56:15 [INFO] Starting TransportServer Informer
2022/03/15 13:56:15 [INFO] Starting IngressLink Informer
2022/03/15 13:56:15 [INFO] Starting ExternalDNS Informer
I0315 13:56:15.722935       1 shared_informer.go:240] Waiting for caches to sync for F5 CIS CRD Controller
I0315 13:56:15.823191       1 shared_informer.go:247] Caches are synced for F5 CIS CRD Controller

2022/03/15 13:59:48 [INFO] No VirtualServers founds in namespace app-l7
2022/03/15 13:59:48 [INFO] No VirtualServers for TransportServer founds in namespace app-l7
2022/03/15 13:59:48 [INFO] No IngressLink founds in namespace app-l7
2022/03/15 13:59:48 [INFO] No VirtualServers founds in namespace app-l7
2022/03/15 13:59:48 [INFO] No VirtualServers for TransportServer founds in namespace app-l7
2022/03/15 13:59:48 [INFO] No IngressLink founds in namespace app-l7
~~~

**Comment by mdditt2000** [comment] 2022-03-21 16:22
Could be related to https://github.com/F5Networks/k8s-bigip-ctlr/issues/2284
Create CONTCNTR-3215 to review

**Comment by trinaths** [comment] 2023-02-02 18:30
Unable to reproduce this issue. Closing this issue.

**Closed by trinaths** 2023-02-02 18:30 UTC
Labels: bug, jira
