### ISSUE TITLE
Different behavior when pool-member-type is cluster or nodeport

### ISSUE THREAD

**Issue by velascoblasco** [F5Networks/k8s-bigip-ctlr#1196] opened 2020-03-05 08:46 UTC
#### Description

When we configure CIS for watching Nodeport resources (Configmap/Ingress) behavior is this:

- If associated Service to Configmap/Ingress is Nodeport then it creates the resource in  BigIP.
   * Pool configured in BigIP will be Nodeport, that is, IP will be K8s node IP. 
- If associated Service to Configmap/Ingress is ClusterIP then it will not create the resource in  BigIP.

When we configure CIS for watching ClusterIP resources (Configmap/Ingress) behavior is this:

- If associated Service to Configmap/Ingress is ClusterIP then it creates the resource in  BigIP.
   * Pool configured in BigIP will be ClusterIP, that is, IP will be K8s pod IP. 
- If associated Service to Configmap/Ingress is Nodeport then it WILL create the resource in  BigIP.
   * Pool configured in BigIP will be ClusterIP, that is, IP will be K8s pod IP. 

I would expect same behavior in both cases. If I configure CIS for pool-member-type clusterIP I do not want CIS creates any configuration in BigIP if the resource is not clusterIP, and even less transform a K8s Nodeport resource into a ClusterIP resource in BigIP.

This happens with CCCL and AS3.

#### Kubernetes Version
v1.14.10

#### Controller Version
v1.13

#### BIG-IP Version
v14.1.0.5

#### Diagnostic Information

kubectl get node -o wide
NAME          STATUS   ROLES    AGE     VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION   CONTAINER-RUNTIME
controller1   Ready    master   56d     v1.14.10   10.10.20.211   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-9-amd64    docker://17.3.2
worker1       Ready    <none>   6d23h   v1.14.10   10.10.20.212   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-9-amd64    docker://17.3.2
worker2       Ready    <none>   6d23h   v1.14.10   10.10.20.213   <none>        Debian GNU/Linux 9 (stretch)   4.9.0-9-amd64    docker://17.3.2

root@controller1:~/as3# kubectl get svc | grep testingnodeport
testingnodeport        NodePort       4.4.6.179     <none>        80:32457/TCP                  15h

root@controller1:~/as3# kubectl get pod -o wide| grep testingnodeport
testingnodeport-6bc489db8-xhlzf         1/1     Running   0          15h     192.168.189.92    worker2   <none>           <none>

root@(localhost)(cfg-sync Standalone)(Active)(/velasco)(tmos)# list ltm pool
ltm pool cfgmap_default_testingnodeport_testingnodeport {
    members {
        192.168.189.92%0:http {
            address 192.168.189.92          <== Pod IP:port
            session monitor-enabled
            state up
        }
    }
    metadata {
        user_agent {
            value k8s-bigip-ctlr-1.13.0-n2182-642304053
        }
    }
    monitor cfgmap_default_testingnodeport_testingnodeport_0_http
    partition velasco
}

**Comment by mdditt2000** [comment] 2020-05-27 20:50
Behavior has changed in CIS 2.0

- ClusterIP FBD are only sent to BIG-IP once the resources is created

Please can you re-test now with CIS 2.0

**Comment by veeramalla-f5** [comment] 2020-07-30 07:11
@velascoblasco It is an expected behaviour.  When a service is created in NodePort Mode, it will be allocated with clusterIP.

Since u have deployed CIS to monitor the services which have clusterIP, CIS honors that service and deploys relevant configuration.

**Comment by mdditt2000** [comment] 2020-08-06 20:24
Closing this issue out. Expected behavior

**Closed by mdditt2000** 2020-08-06 20:24 UTC
Labels: awaiting response, ready to close
