### ISSUE TITLE
New ingress is not updated in BIGIP after python exception occurs.

### ISSUE THREAD

**Issue by type954** [F5Networks/k8s-bigip-ctlr#1776] opened 2021-04-02 07:29 UTC
#### Setup Details
 CIS Version : 2.1.1      
 Build: f5networks/k8s-bigip-ctlr:2.1.1       
 BIGIP Version: Big IP 15.1.2.1      
 AS3 Version: 3.x      
 Agent Mode: CCCL       
 Orchestration: K8S      
 Orchestration Version: 1.17.6    
 Pool Mode: Cluster      
 Additional Setup details: kubernetes, calico, use only ingress.yaml (I don't use configmap)

#### Description  
New ingress is not updated in BIGIP after python exception occurs.
I'm using two BIG-IPs in one k8s cluster.
Although all the settings were the same, the symptoms were only seen in one BIG-IP.
We solved the problem by restarting the bigip controller pod.
But our customers want to know the root cause. Because it can happen again.

#### Steps To Reproduce
Since it is in use service, reproduction test is not possible.

#### Expected Result 
...

#### Actual Result  
...

#### Diagnostic Information
2021/03/30 19:11:53 [INFO] Traceback (most recent call last):
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
2021/03/30 19:11:53 [INFO]     (self._dns_host, self.port), self.timeout, **extra_kw)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
2021/03/30 19:11:53 [INFO]     raise err
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
2021/03/30 19:11:53 [INFO]     sock.connect(sa)
2021/03/30 19:11:53 [INFO] TimeoutError: [Errno 110] Connection timed out
2021/03/30 19:11:53 [INFO] 
2021/03/30 19:11:53 [INFO] During handling of the above exception, another exception occurred:
2021/03/30 19:11:53 [INFO] 
2021/03/30 19:11:53 [INFO] Traceback (most recent call last):
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
2021/03/30 19:11:53 [INFO]     chunked=chunked)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
2021/03/30 19:11:53 [INFO]     self._validate_conn(conn)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
2021/03/30 19:11:53 [INFO]     conn.connect()
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
2021/03/30 19:11:53 [INFO]     conn = self._new_conn()
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
2021/03/30 19:11:53 [INFO]     self, "Failed to establish a new connection: %s" % e)
2021/03/30 19:11:53 [INFO] urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a5b4f0518>: Failed to establish a new connection: [Errno 110] Connection timed out
2021/03/30 19:11:53 [INFO] 
2021/03/30 19:11:53 [INFO] During handling of the above exception, another exception occurred:
2021/03/30 19:11:53 [ERROR] [2021-03-30 19:11:53,952 __main__ ERROR] Unexpected error
2021/03/30 19:11:53 [INFO] 
2021/03/30 19:11:53 [INFO] Traceback (most recent call last):
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
2021/03/30 19:11:53 [INFO]     timeout=timeout
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
2021/03/30 19:11:53 [INFO]     _stacktrace=sys.exc_info()[2])
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
2021/03/30 19:11:53 [INFO]     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2021/03/30 19:11:53 [INFO] urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /mgmt/tm/auth/partition/k8s-service (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a5b4f0518>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2021/03/30 19:11:53 [INFO] 
2021/03/30 19:11:53 [INFO] During handling of the above exception, another exception occurred:
2021/03/30 19:11:53 [INFO] 
2021/03/30 19:11:53 [INFO] Traceback (most recent call last):
2021/03/30 19:11:53 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 325, in _do_reset
2021/03/30 19:11:53 [INFO]     incomplete = self._update_cccl(config)
2021/03/30 19:11:53 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 399, in _update_cccl
2021/03/30 19:11:53 [INFO]     incomplete += mgr._apply_ltm_config(cfg_ltm)
2021/03/30 19:11:53 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 117, in _apply_ltm_config
2021/03/30 19:11:53 [INFO]     return self._cccl.apply_ltm_config(config)
2021/03/30 19:11:53 [INFO]   File "/app/src/f5-cccl/f5_cccl/api.py", line 92, in apply_ltm_config
2021/03/30 19:11:53 [INFO]     self._user_agent)
2021/03/30 19:11:53 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 662, in apply_ltm_config
2021/03/30 19:11:53 [INFO]     default_route_domain = self._bigip.get_default_route_domain()
2021/03/30 19:11:53 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 433, in get_default_route_domain
2021/03/30 19:11:53 [INFO]     name=self._partition)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/f5/bigip/resource.py", line 1054, in load
2021/03/30 19:11:53 [INFO]     return self._load(**kwargs)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/f5/bigip/resource.py", line 1033, in _load
2021/03/30 19:11:53 [INFO]     response = refresh_session.get(base_uri, **kwargs)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/icontrol/session.py", line 257, in wrapper
2021/03/30 19:11:53 [INFO]     response = method(self, REST_uri, **kwargs)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/icontrol/session.py", line 462, in get
2021/03/30 19:11:53 [INFO]     return self.session.get(uri, **kwargs)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/sessions.py", line 537, in get
2021/03/30 19:11:53 [INFO]     return self.request('GET', url, **kwargs)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
2021/03/30 19:11:53 [INFO]     resp = self.send(prep, **send_kwargs)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
2021/03/30 19:11:53 [INFO]     r = adapter.send(request, **kwargs)
2021/03/30 19:11:53 [INFO]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
2021/03/30 19:11:53 [INFO]     raise ConnectionError(e, request=request)
2021/03/30 19:11:53 [INFO] requests.exceptions.ConnectionError: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /mgmt/tm/auth/partition/k8s-service (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a5b4f0518>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2021/03/30 19:11:53 [ERROR] [2021-03-30 19:11:53,955 __main__ ERROR] Error applying config, will try again in 1 seconds

#### Observations (if any)
There is a lot of critical information, so I couldn't upload the file here.
If you can refer to the F5 case you can find a lot of information in "C3540957".

**Comment by trinaths** [comment] 2021-04-05 21:26
`[INFO] requests.exceptions.ConnectionError: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /mgmt/tm/auth/partition/k8s-service (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a5b4f0518>: Failed to establish a new connection: [Errno 110] Connection timed out',))`

Is BIGIP reachable from k8s cluster and partition `k8s-service` exists ?

**Comment by type954** [comment] 2021-04-06 01:48
> `[INFO] requests.exceptions.ConnectionError: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /mgmt/tm/auth/partition/k8s-service (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a5b4f0518>: Failed to establish a new connection: [Errno 110] Connection timed out',))`
> 
> Is BIGIP reachable from k8s cluster and partition `k8s-service` exists ?

Of course there is.
We've been using it well for over 6 months, and only one of the two BIG-IPs has an issue.

**Comment by vincentmli** [comment] 2021-04-16 20:21
@type954 @trinaths I can reproduce this easily with my Perl script https://github.com/vincentmli/Perl/blob/master/ingress-ns.pl. I think you should avoid using agent cccl,using AS3 agent is much better and i have not observed performance issue with CIS 2.3.0 as3 agent.

**Comment by trinaths** [comment] 2021-04-21 13:37
@type954 - Can you try with AS3 agent mode? you have only Ingress ? with as3 mode, configMap processing differs compared with cccl mode.

**Comment by type954** [comment] 2021-04-22 00:20
We only use ingress and this is the first issue so we have to consider whether to change to as3.
We've analyzed the issue, but the symptoms of the python exception and ingress not being updated are out of date.
Do you only recommend as3 for python exceptions?

**Comment by trinaths** [comment] 2021-04-28 17:31
@type954  We recommend AS3 for better performance compared with CCCL. Please try with AS3 mode and share your findings.

**Comment by trinaths** [comment] 2021-05-12 19:28
@type954  any update ?

**Comment by type954** [comment] 2021-05-17 07:30
Please close the case. Thank you for your support.

**Comment by trinaths** [comment] 2021-05-17 11:14
Thank you. Closing this issue.

**Closed by trinaths** 2021-05-17 11:14 UTC
Labels: awaiting response, help wanted
