### ISSUE TITLE
CIS 2.6.0 encountered a crash because of the configuration '--manage-ingress=false' 

### ISSUE THREAD

**Issue by kkfinkkfin** [F5Networks/k8s-bigip-ctlr#2062] opened 2021-10-29 10:23 UTC
#### Setup Details
CIS Version : 2.6.0
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: BIG-IP 15.1.4 Build 0.0.47 Final
AS3 Version: none
Agent Mode: CCCL
Orchestration: K8S
Orchestration Version: kubernetes v1.21.5
Pool Mode: Cluster
Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>
- Platform : CentOS Linux release 8.4.2105
- Kernel: 4.18.0-305.19.1.el8_4.x86_64
- CNI Plugins: flannel

#### Description  
  CIS 2.6.0 encountered a crash because ‘—manage-ingress=false' was configured, this parameter was available before version 2.4.0. 
No parameters were modified, only the image tag was modified and it crashed after upgrading to version 2.6.0 version.

#### Steps To Reproduce
1)The CIS yaml
```CIS yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cc-k8s-to-bigip1
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-bigip-ctlr
    spec:
      containers:
        - name: k8s-bigip-ctlr
          image: 'f5networks/k8s-bigip-ctlr:2.6.0'
          command:
            - /app/bin/k8s-bigip-ctlr
          args:
            - '--bigip-username=admin'
            - '--bigip-password=admin.F5demo.com'
            - '--bigip-url=10.1.20.232'
            - '--bigip-partition=p1'
            - '--pool-member-type=cluster'
            - '--flannel-name=/Common/flannel_vxlan'
            - '--insecure=true'
            - '--log-level=INFO'
            - '--agent=cccl'
            - '--verify-interval=5'
            - '--node-poll-interval=5'
            - '--http-listen-address=0.0.0.0:9113'
            - '--manage-ingress=false'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: bigip-ctlr
      serviceAccount: bigip-ctlr
      nodeName: 172.16.240.6
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```
2) and it carshed

#### Expected Result 
do not crash 

#### Actual Result  
```The CIS log
2021/10/29 09:18:34 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.6.0, BuildInfo: azure-1038-b16efbb771d65d2cfc30dd16f50a8398207f89c8
2021/10/29 09:18:35 [INFO] ConfigWriter started: 0xc0001920c0
2021/10/29 09:18:35 [INFO] Started config driver sub-process at pid: 17
2021/10/29 09:18:35 [INFO] [INIT] Creating Agent for cccl
2021/10/29 09:18:35 [INFO] [CCCL] Initializing CCCL Agent
2021/10/29 09:18:35 [INFO] [CCCL] Removing Partition p1_AS3 

2021/10/29 09:18:35 [INFO] [CORE] NodePoller (0xc0004321b0) registering new listener: 0x17957a0
2021/10/29 09:18:35 [INFO] [CORE] NodePoller (0xc0004321b0) registering new listener: 0x1733980
2021/10/29 09:18:35 [INFO] [CORE] NodePoller started: (0xc0004321b0)
2021/10/29 09:18:35 [INFO] [CORE] Not watching Ingress resources.
2021/10/29 09:18:35 [INFO] [CORE] Watching ConfigMap resources.
2021/10/29 09:18:35 [INFO] [CORE] Handling ConfigMap resource events.
2021/10/29 09:18:35 [INFO] [CORE] Not handling Ingress resource events.
2021/10/29 09:18:35 [INFO] [CORE] Registered BigIP Metrics
E1029 09:18:35.501125       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 90 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19460e0, 0x28b9c10)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x19460e0, 0x28b9c10)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).getSecretServiceQueueKeyForIngress(0xc0002f02c0, 0xc0009cf040, 0x1b6b304, 0x7, 0xc000385ad8)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:192 +0x75
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).checkValidSecrets(0xc0002f02c0, 0x1b48c40, 0xc0009cf040, 0xc00054bdf0, 0xc00054bd40, 0x3, 0x0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:277 +0xe5
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).enqueueSecrets(0xc0002f02c0, 0x1b48c40, 0xc0009cf040, 0x1b6a73e, 0x6)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:827 +0x46
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).newAppInformer.func14(0x1b48c40, 0xc0009cf040)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:752 +0x53
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0001c2f60)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00054bf60, 0x1d5ad20, 0xc0004c2000, 0x1905f01, 0xc0001020c0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0001c2f60, 0x3b9aca00, 0x0, 0xc0002fa401, 0xc0001020c0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00035d580)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004c65a0, 0xc0000ee000)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x16e0575]

goroutine 90 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x19460e0, 0x28b9c10)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).getSecretServiceQueueKeyForIngress(0xc0002f02c0, 0xc0009cf040, 0x1b6b304, 0x7, 0xc000385ad8)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:192 +0x75
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).checkValidSecrets(0xc0002f02c0, 0x1b48c40, 0xc0009cf040, 0xc00054bdf0, 0xc00054bd40, 0x3, 0x0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:277 +0xe5
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).enqueueSecrets(0xc0002f02c0, 0x1b48c40, 0xc0009cf040, 0x1b6a73e, 0x6)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:827 +0x46
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).newAppInformer.func14(0x1b48c40, 0xc0009cf040)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:752 +0x53
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0001c2f60)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008bbf60, 0x1d5ad20, 0xc0004c2000, 0x1905f01, 0xc0001020c0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0001c2f60, 0x3b9aca00, 0x0, 0xc0002fa401, 0xc0001020c0)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00035d580)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004c65a0, 0xc0000ee000)
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65

```

#### Observations (if any)
It also crashed in CIS version 2.5.0+ while it performed well before 2.4.0.

**Comment by luruiqiang** [comment] 2021-11-01 08:22
My customer met the issue too.

**Comment by trinaths** [comment] 2021-11-02 15:12
created CONTCNTR-3000 for internal tracking

**Comment by myf5** [comment] 2021-11-08 02:57
+1 weight

**Comment by trinaths** [comment] 2021-11-09 18:59
@kkfinkkfin - were there any secrets in the environment being processed by CIS ? From CIS 2.5 we are monitoring changes to K8S secrets. Unable to reproduce this issue. Please share more info.

**Comment by trinaths** [comment] 2021-11-09 19:02
Please share steps to reproduce this issue.

**Comment by kkfinkkfin** [comment] 2021-11-10 01:06
> @kkfinkkfin - were there any secrets in the environment being processed by CIS ? From CIS 2.5 we are monitoring changes to K8S secrets. Unable to reproduce this issue. Please share more info.

There are no secrets in the env processed by CIS.  just processed the cccl mode configmaps.  If you use both --manage-ingress=false' and the '--namespace-label' which namespace do not have ingress that is ok.  So you may remove the '--namespace-label' and it can be reproduced 100%.

**Comment by trinaths** [comment] 2021-11-11 10:12
unable to reproduce this issue. toggle between --manage-ingress=true or false does not crash the controller 2.5,2.6 and 2.6.1. Changed toggle namespace-label still not found.

**Comment by luruiqiang** [comment] 2021-11-12 05:31
> unable to reproduce this issue. toggle between --manage-ingress=true or false does not crash the controller 2.5,2.6 and 2.6.1. Changed toggle namespace-label still not found.

if I replace "image: f5networks/k8s-bigip-ctlr:2.6.1" to "image: f5networks/k8s-bigip-ctlr:2.4.1", the CIS pod is ok. 
my yaml of cis is: 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-bigip-controller-1
  namespace: kube-system
  labels:
    app: f5-bigip-controller-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-bigip-controller-1
  template:
    metadata:
      name: f5-bigip-controller-1
      labels:
        app: f5-bigip-controller-1
    spec:
      serviceAccountName: bigip-ctlr
      containers:
        - name: f5-bigip-controller-1
          image: f5networks/k8s-bigip-ctlr:2.6.1
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: f5-secret
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: f5-secret
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.1.10.241",
            "--insecure=true",
            "--verify-interval=10",
            "--bigip-partition=k8s",
            "--agent=AS3",
            "--manage-ingress=false",
            "--pool-member-type=cluster",
            "--log-as3-response=true"
            ]

**Comment by trinaths** [comment] 2021-11-12 07:32
CIS is not validated compatible with k8s 1.22. I have tested CIS 2.6.1 in 1.21 K8S and see no crash issues. Based on debug session I learn that CIS is deployed in Rancher k8s environment where CIS is not validated yet. Suggest to try this deployment on 1.21 k8s and check for any crash and share your findings.

**Comment by myf5** [comment] 2021-11-16 00:41
> CIS is not validated compatible with k8s 1.22. I have tested CIS 2.6.1 in 1.21 K8S and see no crash issues. Based on debug session I learn that CIS is deployed in Rancher k8s environment where CIS is not validated yet. Suggest to try this deployment on 1.21 k8s and check for any crash and share your findings.

Can you try to install the nginx IC in your environment, we found once we install both of all them, cis will crash.

**Comment by trinaths** [comment] 2021-11-16 19:53
Closing this issue. With Nginx IC in place, no crash observed in CIS. recommend check the environment and other resources.

**Closed by trinaths** 2021-11-16 19:53 UTC
Labels: bug, awaiting response, jira
