### ISSUE TITLE
[BUG]Both clientssl annotation and cert/key provided for Route in log

### ISSUE THREAD

**Issue by rvalkenaers** [F5Networks/k8s-bigip-ctlr#805] opened 2019-01-15 09:24 UTC
#### Description
Following line gets logged every ~5 seconds  even though only the annotation is specified:
2019/01/15 08:55:28 [INFO] Both clientssl annotation and cert/key provided for Route: test-app, using annotation.

#### Kubernetes Version
Openshift v3.9
Kubernetes v1.9

#### Controller Version
v1.7.0

##### Route config
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    virtual-server.f5.com/clientssl: /Common/test-cert
  creationTimestamp: '2018-12-20T09:33:39Z'
  name: test-app
  namespace: test
  resourceVersion: '45187737'
  selfLink: /apis/route.openshift.io/v1/namespaces/test/routes/test-app
  uid: 55417839-043a-11e9-a9c9-f20180053384
spec:
  host: app.test.com
  path: /
  port:
    targetPort: test-app
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-app
    weight: 100
  wildcardPolicy: None
status:
  ingress: null
```
##### Log:
2019/01/15 09:07:58 [INFO] Both clientssl annotation and cert/key provided for Route: test-app, using annotation.

**Comment by vincentmli** [comment] 2019-01-30 19:56
the code probably should be as below as the log intended to do
<pre>

diff --git a/pkg/appmanager/profiles.go b/pkg/appmanager/profiles.go
index 74266ed..c15048d 100644
--- a/pkg/appmanager/profiles.go
+++ b/pkg/appmanager/profiles.go
@@ -73,7 +73,8 @@ func (appMgr *Manager) setClientSslProfile(
        // Now handle the profile from the Route.
        // If annotation is set, use that profile instead of Route profile.
        if prof, ok := route.ObjectMeta.Annotations[f5ClientSslProfileAnnotation]; ok {
-               if nil != route.Spec.TLS {
+               if nil != route.Spec.TLS &&
+                       "" != route.Spec.TLS.Certificate && "" != route.Spec.TLS.Key {
                        log.Infof("Both clientssl annotation and cert/key provided for Route: %s, "+
                                "using annotation.", route.ObjectMeta.Name)
                        // Delete existing Route profile if it exists


</pre>

**Comment by mdditt2000** [comment] 2019-04-18 23:14
@kavitha-f5 Can you have somebody from the team scope this and identify if a bug

**Comment by ssurenr** [comment] 2019-04-24 06:01
I'll try to reproduce this and give an update.

**Comment by mdditt2000** [comment] 2019-06-07 18:33
https://jira.pdsea.f5net.com/browse/CONTCNTR-603

**Comment by mdditt2000** [comment] 2019-08-09 11:05
Issue is resolved and will ship in CIS 1.10 August 21st

**Comment by mdditt2000** [comment] 2019-08-09 11:06
Closing issue out

**Closed by mdditt2000** 2019-08-09 11:06 UTC
Labels: 1.10

**Comment by sbarre-esit** [comment] 2020-03-16 21:17
I'm getting this still with the latest image.

**Comment by mdditt2000** [comment] 2020-03-16 21:21
@sbarre-esit please can you open a new issue with what you are seeing. Please provide your route + controller config. Please remove sensitive data. Thanks Mark
