### ISSUE TITLE
422 null exception

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2784] opened 2023-02-23 08:02 UTC
#### Setup Details
 CIS Version : 2.11.1 
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1
 AS3 Version: 3.41
 Agent Mode: AS3      
 Orchestration: K8S      
 Orchestration Version:       
 Pool Mode: Cluster     
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
When I delete virtualServers I get a 422 error (null execption) on the first try and then the AS3 (from CIS) is successful. 
Below are the logs from CIS
```
2023/02/23 06:07:39 [ERROR] [AS3] Raw response from Big-IP: map[code:422 kind::resterrorresponse message:request failed with null exception referer:10.1.20.20 restOperationId:6.66517e+06] {"$schema":"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.41.0/as3-schema-3.41.0-1.json","class":"AS3","declaration":{"cis-crd":{"Shared":{"app_10_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.10"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_10_80__policy"},"app_10_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_10_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_10_8080_default"}}}]}],"strategy":"first-match"},"app_2_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.2"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_2_80__policy"},"app_2_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_2_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_2_8080_default"}}}]}],"strategy":"first-match"},"app_3_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.3"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_3_80__policy"},"app_3_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_3_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_3_8080_default"}}}]}],"strategy":"first-match"},"app_4_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.4"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_4_80__policy"},"app_4_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_4_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_4_8080_default"}}}]}],"strategy":"first-match"},"app_5_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.5"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_5_80__policy"},"app_5_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_5_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_5_8080_default"}}}]}],"strategy":"first-match"},"app_6_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.6"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_6_80__policy"},"app_6_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_6_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_6_8080_default"}}}]}],"strategy":"first-match"},"app_7_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.7"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_7_80__policy"},"app_7_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_7_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_7_8080_default"}}}]}],"strategy":"first-match"},"app_8_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.8"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_8_80__policy"},"app_8_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_8_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_8_8080_default"}}}]}],"strategy":"first-match"},"app_9_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["192.168.1.9"],"virtualPort":80,"snat":"auto","policyEndpoint":"/cis-crd/Shared/app_9_80__policy"},"app_9_80__policy":{"class":"Endpoint_Policy","rules":[{"name":"vs__app_svc_9_8080_default","actions":[{"type":"forward","event":"request","select":{"pool":{"use":"app_svc_9_8080_default"}}}]}],"strategy":"first-match"},"app_svc_10_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.3.7"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.5.10"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_10_default_http_8080"}]},"app_svc_10_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"app_svc_2_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.1.3"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.5.3"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_2_default_http_8080"}]},"app_svc_2_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"app_svc_3_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.1.4"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.3.4"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_3_default_http_8080"}]},"app_svc_3_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"app_svc_4_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.4.4"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.5.5"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_4_default_http_8080"}]},"app_svc_4_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"app_svc_5_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.3.5"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.4.5"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_5_default_http_8080"}]},"app_svc_5_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"app_svc_6_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.2.5"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.4.6"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_6_default_http_8080"}]},"app_svc_6_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"app_svc_7_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.2.6"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.5.7"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_7_default_http_8080"}]},"app_svc_7_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"app_svc_8_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.2.8"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.5.6"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_8_default_http_8080"}]},"app_svc_8_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"app_svc_9_8080_default":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.244.2.7"],"servicePort":8080,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["10.244.3.6"],"servicePort":8080,"shareNodes":true}],"monitors":[{"use":"/cis-crd/Shared/app_svc_9_default_http_8080"}]},"app_svc_9_default_http_8080":{"class":"Monitor","interval":10,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /rn"},"class":"Application","template":"shared"},"class":"Tenant","defaultRouteDomain":0},"class":"ADC","controls":{"class":"Controls","userAgent":"CIS/v2.11.1 K8S/v1.20.15"},"id":"urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d","label":"CIS Declaration","remark":"Auto-generated by CIS","schemaVersion":"3.41.0"}
```

At the same time I got the error from BIGP logs
```
Thu, 23 Feb 2023 06:07:34 GMT - finest: socket 228 opened
Thu, 23 Feb 2023 06:07:36 GMT - severe: [appsvcs] {"message":"Declaration failed: The connection to mcpd has been lost, try again.","level":"error"}
Thu, 23 Feb 2023 06:07:39 GMT - finest: socket 228 closed
 
==> /var/log/restjavad.0.log <==
[WARNING][1573][23 Feb 2023 06:07:39 UTC][RestOperation] Unable to generate error body for POST http://localhost:8100/mgmt/shared/appsvcs/declare/cis-crd 422: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2049 path $.declaration.cis-crd.Shared.app_4_80.source
        at com.google.gson.internal.Streams.parse(Streams.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:84)
        at com.google.gson.JsonParser.parse(JsonParser.java:59)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.f5.rest.common.RestOperation.toJsonTree(RestOperation.java:2765)
        at com.f5.rest.common.RestOperation.getParsedBody(RestOperation.java:1685)
        at com.f5.rest.common.RestOperation.fail(RestOperation.java:2459)
        at com.f5.rest.common.RestOperation.fail(RestOperation.java:2413)
        at com.f5.rest.workers.ForwarderPassThroughWorker$2.failed(ForwarderPassThroughWorker.java:641)
        at com.f5.rest.workers.ForwarderPassThroughWorker$2.failed(ForwarderPassThroughWorker.java:573)
        at com.f5.rest.common.RestOperation.fail(RestOperation.java:2493)
        at com.f5.rest.common.RestOperation.fail(RestOperation.java:2413)
        at com.f5.rest.common.ApacheAsyncRequestSender$3.run(ApacheAsyncRequestSender.java:528)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 2049 path $.declaration.cis-crd.Shared.app_4_80.source
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:697)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 19 more
```

#### Steps To Reproduce
1) I attached the declarations that I have used including the CIS. 

I have tried with different AS3 versions and CIS version (2.10), but I get the same result.

[300.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/10811404/300.txt)
[cis-ctlr-crd-2.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/10811402/cis-ctlr-crd-2.txt)
[deploy-apps.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/10811403/deploy-apps.txt)

**Comment by trinaths** [comment] 2023-02-24 09:33
Unable to reproduce this issue. Closing this for now.

**Closed by trinaths** 2023-02-24 09:33 UTC
Labels: bug, untriaged

**Comment by nusrath432** [comment] 2023-05-26 14:55
@trinaths  I am seeing this error again on CIS/v2.12.1 K8S/v1.25.10 Nginx/v2.4.2 and Nginx/v3.1.1:
```
2023/05/26 14:31:07 [ERROR] [AS3] Raw response from Big-IP: map[code:422 kind::resterrorresponse message:request failed with null exception referer:10.20.20.230 restOperationId:2.1817906e+07] {"$schema":"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.41.0/as3-schema-3.41.0-1.json","class":"AS3","declaration":{"class":"ADC","controls":{"class":"Controls","userAgent":"CIS/v2.12.1 K8S/v1.25.10"},"id":"urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d","k8snonprod":{"Shared":{"class":"Application","template":"shared"},"class":"Tenant"},"label":"CIS Declaration","remark":"Auto-generated by CIS","schemaVersion":"3.41.0"}}
```

Tried without irules
```
apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: 10.20.20.184
  selector:
    matchLabels:
      app: nginx-ingress
```

Even with labels / irules:
```
apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.20.20.184"
  host: cafe.example.com
  partition: k8snonprod
  iRules:
    - /Common/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: nginx-ingress
```


Service deployed:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-ingresslink
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: readiness-port
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: nginx-ingress
  type: NodePort
```

It happens once the CIS/Nginx deployment is done; last step of createing ingresslink - guess something is missing in the ingresslink format?

**Comment by nusrath432** [comment] 2023-05-31 01:23
@trinaths - I had to delete the partition and let the IngressLink object create the partition again - that seems to have worked.
