### ISSUE TITLE
Documentation Bug:  IngressLink compatibility matrix needs updating

### ISSUE THREAD

**Issue by dstrohl** [F5Networks/k8s-bigip-ctlr#1825] opened 2021-05-12 15:43 UTC
from page: https://clouddocs.f5.com/containers/latest/userguide/ingresslink/

The compatibility matrix lists the CIS version required as 2.3+, however for use in a ClusterIP deployment it must be at least 2.4.

It should also mention the required AS3 version if that is important.

Expected:

Minimum version to use IngressLink:

| CIS | BIGIP | NGINX+ IC | AS3 |
| ------ | ------ | ------ | ------ |
| 2.4+ (ClusterIP) | v13.1+ | 1.10+ | 3.18+ | 
| 2.3+ (NodePort) | v13.1+ | 1.10+ | 3.18+ |

**Comment by trinaths** [comment] 2021-05-12 19:10
Created CONTCNTR-2672 for PM tracking

**Comment by vtrippel** [comment] 2021-05-14 21:07
Thank you for the feedback Dan. I've just fixed this and it will be published with the next minor release.

**Comment by trinaths** [comment] 2021-05-21 11:51
The issue is fixed. Document updated. Closing this issue.

**Closed by trinaths** 2021-05-21 11:51 UTC
Labels: bug, jira
