### ISSUE TITLE
Controller writing 0 vservers after some time

### ISSUE THREAD

**Issue by fefl** [F5Networks/k8s-bigip-ctlr#418] opened 2017-11-09 17:12 UTC
#### Description
Bug: We are running a single instance big-ip with a container controller in an openshift cluster. The setup was running over the weekend. When we came back on monday all configurations that are handled by the CC were reset. We had a look into the logs and they kept reporting `Updated 0 of 0 virtual server configs, deleted 0`. After restarting the Controller it was writing the vservers and pools again. The Openshift Routes we created were working. After some minutes the controller was again reporting the same error and routes did not work anymore.
The configuration of the deployment for the controller and the logs of the pod are attached to this issue.
If there is any more information you need and that I can provide please tell me.

#### Openshift Version
3.5 (Kubernetes 1.5)

#### Controller Version
1.2

#### BIG-IP Version
12.1.2

#### Diagnostic Information
[debug.log](https://github.com/F5Networks/k8s-bigip-ctlr/files/1458472/debug.log)
[controller_deployment.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/1458475/controller_deployment.txt)
[routes.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/1459047/routes.txt)
[services.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/1459048/services.txt)

**Comment by f5gary** [comment] 2017-11-09 17:51
@fefl The debug.log file shows that 0 virtual servers are being configured as you mention, but it does not show any period when they were being configured correctly or anything that occurred before they stopped being configured. If you have logs that show that information, please provide us with that, and also your Route and Service configurations (after you have removed anything confidential from them). Thank you.

**Comment by fefl** [comment] 2017-11-09 20:10
@f5gary I added the services and route definitions to the initial post. unfortunately we do not have any logs that show the working behaviour and the failing behaviour. We will try to reproduce the issue to provide the requested information.

**Comment by f5gary** [comment] 2017-11-13 17:54
I have been trying to reproduce this issue without success. I have tested where the OpenShift configuration was static as well as with periodic changes, and the controller always maintained a valid configuration on the BIG-IP. @fefl have you been able to reproduce this with debug logging enabled during the time the virtual servers were deconfigured? Also it would be helpful if you could provide us with diffs showing any modifications you have made to the controller code.

**Comment by f5gary** [comment] 2017-11-28 16:49
I am closing this issue since I have not been able to reproduce this error. @fefl please feel free to reopen this issue if you are still experiencing this and can provide some additional logging. Thank you.

**Closed by f5gary** 2017-11-28 16:49 UTC
Labels: P1
