### ISSUE TITLE
BIG-IP Controller cannot detect to increase or decrease number of pods

### ISSUE THREAD

**Issue by altblanc** [F5Networks/k8s-bigip-ctlr#1019] opened 2019-09-11 08:59 UTC
#### Description
With using AS3, k8s-bigip-ctlr cannot detect to change the number of pods.  
Our k8s-bigip-ctlr is working on cluster-mode.I followed [this document](https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html#cis-and-partitions) for deploying AS3 object.  
First detection is correct, but if I change my deployment, k8s-bigip-ctlr cannot detect it, so pod's ips are not changed and pool is down.

here is my AS3 configmap.

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: as3-declaration
  namespace: kube-system
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.11.0",
        "id": "as3-declaration",
        "label": "application",
        "remark": "HTTPS definition for app1",
        "AS3": {
          "class": "Tenant",
          "app1": {
            "class": "Application",
            "template": "https",
            "serviceMain": {
              "class": "Service_HTTPS",
              "redirect80": false,
              "iRules": [
                {"bigip":"/Common/iRule1"},
                {"bigip":"/Common/iRule2"}
              ],
              "virtualAddresses": [
                "10.3.115.22"
              ],
              "serverTLS": {"bigip":"/Common/app1"},
              "profileHTTP": {
                "bigip": "/Common/http_for_https"
              },
              "profileHTTP2": {
                "bigip": "/Common/http2_client"
              },
              "pool": "app1_pool"
            },
            "app1_pool":{
              "class":"Pool",
              "monitors":[
                "http"
              ],
              "members":[
                {
                  "servicePort":8080,
                  "serverAddresses":[]
                }
              ]
            }
          },
          "app2": {
            "class": "Application",
            "template": "generic",
            "app2": {
              "class": "Service_HTTPS",
              "redirect80": false,
              "virtualAddresses": [
                "10.3.115.23"
              ],
              "iRules": [
                {"bigip":"/Common/iRule1"},
                {"bigip":"/Common/iRule2"}
              ],
              "serverTLS": {"bigip":"/Common/app2"},
              "profileHTTP": {
                "bigip": "/Common/http_for_https"
              },
              "profileHTTP2": {
                "bigip": "/Common/http2_client"
              },
              "pool": "app2_pool"
            },
            "app2_pool":{
              "class":"Pool",
              "monitors":[
                "http"
              ],
              "members":[
                {
                  "servicePort":8080,
                  "serverAddresses":[]
                }
              ]
            }
          },
          "app3": {
            "class": "Application",
            "template": "generic",
            "menu": {
              "class": "Service_HTTPS",
              "redirect80": false,
              "virtualAddresses": [
                "10.3.115.24"
              ],
              "iRules": [
                {"bigip":"/Common/iRule1"},
                {"bigip":"/Common/iRule1"}
              ],
              "serverTLS": {"bigip":"/Common/app3"},
              "profileHTTP": {
                "bigip": "/Common/http_for_https"
              },
              "profileHTTP2": {
                "bigip": "/Common/http2_client"
              },
              "pool": "app3_pool"
            },
            "app3_pool":{
              "class":"Pool",
              "monitors":[
                "http"
              ],
              "members":[
                {
                  "servicePort":8080,
                  "serverAddresses":[]
                }
              ]
            }
          }
        }
      }
    }
```

my deployment and service are below.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: application
  labels:
    app.kubernetes.io/name: app1
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: app1
    tier: frontend
spec:
  replicas: 50
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      namespace: application
      labels:
        app.kubernetes.io/name: app1
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: app1
        tier: frontend
        app: app1
    spec:
      containers:
      - name: app1
        image: my.private.registry/applications/app1:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
          - name: app1-secrets
            mountPath: /app1/config/credentials.yml.enc
            subPath: credentials.yml.enc
          - name: app1-secrets
            mountPath: /app1/config/master.key
            subPath: master.key
          - name: pv-app1-volume
            mountPath: "/mnt/nfs"
      volumes:
        - name: app1-secrets
          secret:
            secretName: app1-sct
            defaultMode: 420 
        - name: pv-app1-volume
          persistentVolumeClaim:
            claimName: pv-app1
---
kind: Service
apiVersion: v1
metadata:
  name: app1
  namespace: application
  labels:
    app.kubernetes.io/name: app1
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: app1
    tier: frontend
    app: app1
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: app1
    cis.f5.com/as3-pool: app1_pool
spec:
  selector:
    app: app1
  ports:
  - name: http8080
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

```

#### Kubernetes Version
1.13.1

#### Controller Version
1.10.0

#### BIG-IP Version
1.14.1

**Comment by mdditt2000** [comment] 2019-09-11 17:08
@altblanc looking at this today.

**Comment by mdditt2000** [comment] 2019-09-11 20:54
Configuration is correct. Opened Jira CONTCNTR-1053 and assigned to current sprint for PD to pickup. @altblanc thank you for reporting this. I will get this assigned to development to look into more.

**Comment by altblanc** [comment] 2019-09-12 00:09
@mdditt2000 thank you for your response. And there is lack of information about AS3 version in my issue. its version is `3.13.1`.

**Comment by mdditt2000** [comment] 2019-09-12 02:43
Dev is looking at the issue. CIS 1.10 was tested and validated with AS3.11. We plan to test using AS3.13.1 for CIS 1.11. Is it possible to move to AS3.11?

**Comment by altblanc** [comment] 2019-09-12 04:13
Ok, I'll try.

**Comment by altblanc** [comment] 2019-09-12 05:32
I tried 3.11 but I couldn't. Maybe I need to reconfigure AS3 ConfigMap?  
I tried like below:
- `kubectl delete -f app1-deployment.yaml` for deleting pods.
- after all pods are disappeared, I done`kubectl apply -f app1-deployment.yaml`.
- the number of pool members remains and some members are down(because pods are moved or deleted).  

I also tried `kubectl apply -f app1-deployment.yaml`, but the same has occurred.

**Comment by mdditt2000** [comment] 2019-09-12 05:54
Thanks for the update. Dev is looking at this issue. Thanks for trying.

**Comment by mdditt2000** [comment] 2019-10-01 21:51
hello @altblanc we cannot reproduce your issue and have determined there is an issue with the AS3 configmap. I was also seeing another issue where we were seeing the same error and it was a AS3 configmap to service. Please can we open a SR for AS3 assistance or reach out to me so i can help figure out whats the issue with the configmap. Thanks Mark

**Comment by mdditt2000** [comment] 2019-10-15 04:15
Closing issue. This is not a issue with CIS.

**Closed by mdditt2000** 2019-10-15 04:15 UTC
