### ISSUE TITLE
k8s-bigip-ctlr 1.5.1 attempting to remove BIGIP clientssl profile 

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#710] opened 2018-06-15 21:09 UTC
#### Description

a client ssl profile test-clientssl is pre-created in BIGIP partition "test", then deploy k8s-bigip-ctrl 1.4.2 to manage the "test" partition, deploy ingress to reference the clientssl profile in the "test" partition:

<pre>
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: single-service
  annotations:
     'virtual-server.f5.com/ip': '10.169.72.169'
     'virtual-server.f5.com/health': |
      [
        {
          "path":     "/",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  16
        }
      ]
spec:
  tls:
  - secretName: test/test-clientssl #<===test-clientssl under test partition
  backend:
    serviceName: nginxservice
    servicePort: 80
</pre>

this works fine for 1.4.2 and 1.4.1 and 1.3.x.

but if upgrading the k8s-bigip-ctrl to 1.5.1 by below order:

<pre>
- Running version 1.4.2 exhibited no issues
- Removed k8s-bigip-ctrl 1.4.2 deployment,  BIGIP kept the ingress virtual, client ssl profile in "test" partition

- Deployed k8s-bigip-ctrl 1.5.1 deployment, BIGIP kept the ingress virtual, client ssl profile in 
 "test" partition, k8s-bigip-ctrl 1.5.1 complains:

   "Jun 15 11:18:44 k8s-vcmp notice icrd_child[10585]: 01420002:5: AUDIT - pid=10585 user=admin folder=/Common module=(tmos)# status=[01070265:3: The ClientSSL Profile (/test/test-clientssl) cannot be deleted because it is in use by a virtual server profile (/test/ingress_10-169-72-169_443 /test/test-clientssl).] cmd_data=delete ltm profile client-ssl /test/test-clientssl
"

- Removed k8s-bigip-ctrl 1.5.1 deployment,  BIGIP kept the ingress virtual, client ssl profile in k8s partition

- Re-deployed k8s-bigip-ctrl 1.4.2 deployment, BIGIP kept the ingress virtual, client ssl profile in k8s partition, no k8s-bigip-ctrl log error.
</pre>

we want to know what changes made between 1.4.2 and 1.5.1 to enforce k8s-bigip-ctrl 1.5.1 to attempt to remove the test-clientssl profile in "test" partition and that the test-clientssl profile is not managed by k8s-bigip-ctrl

we understand the practices is to let k8s-bigip-ctrl to manage  the partition solely without the interference of other BIGIP tmsh/GUI/iapp utilities, but we want to understand why 1.4.2 allow test-clientssl exist in the partition managed by k8s-bigip-ctrl, 1.5.1 doesn't.

#### Kubernetes Version
k8s version is irrelevant

#### Controller Version
1.5.1
#### BIG-IP Version
13.1.0.4
#### Diagnostic Information

Jun 15 11:18:44 k8s-vcmp notice icrd_child[10585]: 01420002:5: AUDIT - pid=10585 user=admin folder=/Common module=(tmos)# status=[01070265:3: The ClientSSL Profile (/test/test-clientssl) cannot be deleted because it is in use by a virtual server profile (/test/ingress_10-169-72-169_443 /test/test-clientssl).] cmd_data=delete ltm profile client-ssl /test/test-clientssl

**Comment by vincentmli** [comment] 2018-06-15 21:12
sorry I reference the log error from BIGIP audit log, the actual k8s-bigip-ctrl 1.5.1 error log looks similar to that

**Comment by vincentmli** [comment] 2018-06-19 20:29
from test creating client ssl profile in separate new partition, the controller will not allow anything outside of the partition it manages or the /Common partition.  Therefore any profiles that are referenced must be in the Common partition

2018/06/19 19:47:21 [ERROR] [2018-06-19 19:47:21,515 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.184.100.77:443/mgmt/tm/ltm/virtual/
2018/06/19 19:47:21 [INFO] Text: u'{"code":400,"message":"01070726:3: A virtual server may only reference profiles in the same partition or the common partition (/RIS-INT-DAL12/ingress_9-59-154-61_443:/Profiles/BlueMix)","errorStack":[],"apiError":3}'

**Comment by dgarrisonf5** [comment] 2018-10-23 22:04
By design, Container Connector will remove any objects that exist in a BIG-IP partition that don't have a representation in the container ecosystem.  Unclear as to why this behavior wasn't observed in v1.4.2.

Closing issue

**Closed by dgarrisonf5** 2018-10-23 22:04 UTC
Labels: P3, help wanted
