### ISSUE TITLE
Removing and/or renaming a k8s service break CIS

### ISSUE THREAD

**Issue by rlombardi12** [F5Networks/k8s-bigip-ctlr#1396] opened 2020-07-10 17:34 UTC
Title
Removing and/or renaming a k8s service exposed by CIS without prior removing the ingress break CIS

Description
If we remove a service exposed by CIS 2.0 without removing first the ingress, the CIS break and stops updating configuration in BigIP. We need to delete and re-deploy the Controller to start working again.

Actual Problem
Today if we remove a service that is being referenced by an ingress, it simply break the controller. Every update done after this is not reflected in BigIP.

Solution Proposed
If a service exposed by CIS ingress is removed, the controller should identify and remove configuration in BigIP as the service dont exist anymore.

Alternatives
We need to take care and first delete the ingress and then delete/rename the service. This is impacting customer operations. 

Important log from Controller

2020/07/10 14:46:11 [ERROR] [AS3] Big-IP Responded with code: 422
**2020/07/10 14:46:11 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/dict_AS3/Shared/ingress_10_138_0_4_80/pool: contains path to non-existent object ingress_dict_nginx] message:declaration is invalid]**
2020/07/10 14:46:33 [INFO] [CORE] Port '8080' for service 'nginx' was not found.
2020/07/10 14:46:33 [INFO] [CORE] Service 'nginx' has not been found.

**Comment by cisbotctlr** [comment] 2020-07-10 17:34
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by veeramalla-f5** [comment] 2020-07-29 11:29
@rlombardi12 CIS has service informers which does exactly what you have asked for. I am surprised it is not doing the same. Do you have both service and ingress in the same namespace or different.

I will try to reproduce the issue and get back to you.

**Comment by rlombardi12** [comment] 2020-07-29 12:00
@veeramalla-f5 the test was done in the same namespace. You can easily reproduce it. Just remove the service prior the ingress and things start getting strange. Customer is complaining that this is impacting their operations.

**Comment by mdditt2000** [comment] 2020-07-30 06:16
duplicate of https://github.com/F5Networks/k8s-bigip-ctlr/issues/1417

**Comment by iam-veeramalla** [comment] 2021-05-04 01:20
@trinaths can you please close it as duplicate or assign it to someone else? Thanks 👍

**Comment by trinaths** [comment] 2021-07-06 18:52
duplicate of #1417 closing this issue.

**Closed by trinaths** 2021-07-06 18:52 UTC
Labels: In progress, duplicate
