### ISSUE TITLE
Upgrade to 2.9.1 from 2.8.1 - Health Check not Working

### ISSUE THREAD

**Issue by jmorello-mdsol** [F5Networks/k8s-bigip-ctlr#2538] opened 2022-08-09 16:09 UTC
After upgrading to CIS 2.9.1 from 2.8.1, a virtualServer health check is no longer working. Big-IP AS3 Plugin version 3.30.
This is the health check.

 monitor:
      type: http
      send: "/ HTTP/1.1\r\nHost: \r\nConnection: Close\r\n\r\n"
      interval: 5   # <-- Optional
      timeout: 16   # <-- Optional

We receive this error. The only thing that appears to work is 'send: /' #2537 

[ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/k8s-crd-grncl002/Shared: propertyName "f5_hello_world_2_default_http_8080_ HTTP_1_1\r\nHost_ \r\nConnection_ Close\r\n\r\n" should match pattern "^[A-Za-z]([0-9A-Za-z_.-]{0,188}[0-9A-Za-z_.])?$"] message:declaration is invalid] {"$schema":"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.18.0/as3-schema-3.18.0-4.json","class":"AS3","declaration":{"class":"ADC","controls":{"class":"Controls","userAgent":"CIS/v2.9.1 K8S/
~
~

**Comment by trinaths** [comment] 2022-08-09 16:42
Duplicate of https://github.com/F5Networks/k8s-bigip-ctlr/issues/2507

**Closed by trinaths** 2022-08-09 16:42 UTC
