### ISSUE TITLE
CC logs 

### ISSUE THREAD

**Issue by liaotx** [F5Networks/k8s-bigip-ctlr#1255] opened 2020-04-27 07:39 UTC
#### Description
in my k8s env ,i used CC and deployment configmap( used iapp to deployment them), i want to knew about two things.
1. in CC log  ,the info has keep scrolling ，and them is normal ?
2. if the info keep scrolling, when someday them will too much to storage？

#### Kubernetes Version
<Version of Kubernetes being used>

#### Controller Version
GitVersion:"v1.16.3"

#### BIG-IP Version
V1.11

#### Diagnostic Information
2020/01/14 02:41:31 [WARNING] Overwriting existing entry for backend {ServiceName:nginxservice ServicePort:80 Namespace:default}
2020/01/14 02:41:31 [WARNING] Overwriting existing entry for backend {ServiceName:nginxservice ServicePort:80 Namespace:default}
2020/01/14 02:41:31 [WARNING] Overwriting existing entry for backend {ServiceName:nginxservice ServicePort:80 Namespace:default}
2020/01/14 02:41:31 [WARNING] Overwriting existing entry for backend {ServiceName:nginxservice ServicePort:80 Namespace:default}
2020/01/14 02:41:31 [INFO] Wrote 0 Virtual Server and 4 IApp configs
2020/01/14 02:41:31 [INFO] [2020-01-14 02:41:31,666 f5_cccl.resource.resource INFO] Updating ApiApplicationService: /service/default_iapp-http
2020/01/14 02:41:31 [INFO] [2020-01-14 02:41:31,793 f5_cccl.resource.resource INFO] Updating ApiApplicationService: /service/default_iapp-https
2020/01/14 02:41:31 [INFO] [2020-01-14 02:41:31,930 f5_cccl.resource.resource INFO] Updating ApiApplicationService: /service/default_iapp-tcp
2020/01/14 02:41:32 [INFO] [2020-01-14 02:41:32,611 f5_cccl.resource.resource INFO] Updating ApiApplicationService: /service/default_iapp-http
2020/01/14 02:41:32 [INFO] [2020-01-14 02:41:32,748 f5_cccl.resource.resource INFO] Updating ApiApplicationService: /service/default_iapp-https
2020/01/14 02:41:32 [INFO] [2020-01-14 02:41:32,893 f5_cccl.resource.resource INFO] Updating ApiApplicationService: /service/default_iapp-tcp

**Comment by liaotx** [comment] 2020-04-27 07:41
update my info ：
Kubernetes Version
GitVersion:"v1.16.3"

Controller Version
V1.11

BIG-IP Version
V13.1.3

**Comment by mdditt2000** [comment] 2020-04-27 20:12
Internal verification to determine if this is the same as Gitlab issue issues/345. Please standby while triaged.

**Comment by mdditt2000** [comment] 2020-04-28 18:43
Hi @liaotx - CIS team has looked into these errors. This issue seems to be not reproduced in our environment. We observed this behavior when more than one route/configmap configured with a same host name. Can we please cross check the above configurations? 

If you environment then, can we get more details on env like, number of services, number of routes, service-route association etc. so that it helps us in further trouble shooting this issue.

**Comment by liaotx** [comment] 2020-04-28 19:35
thanks for your responsed ,i want to description my k8s env, i used iapp tmpl to deployment my configmap.yaml (i has 7 kind tmpl and yaml,but only if i deployment 1 them still loging),and every times i deployment configmap when always logs that info. ,i want to know why it will be logs out and that is't normal?

that is my iapp-tmpl and configmap-yaml and my F5 info
#############################################
##########here is 1 configmap logs################
2020/01/14 06:57:14 [INFO] [2020-01-14 06:57:14,150 f5_cccl.resource.resource INFO] Updating ApiApplicationService: /service/default_iapp-tcp
2020/01/14 06:57:22 [WARNING] Overwriting existing entry for backend {ServiceName:nginxservice ServicePort:80 Namespace:default}
2020/01/14 06:57:22 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/01/14 06:57:22 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/01/14 06:57:22 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/01/14 06:57:22 [WARNING] Overwriting existing entry for backend {ServiceName:nginxservice ServicePort:80 Namespace:default}
2020/01/14 06:57:22 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/01/14 06:57:22 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/01/14 06:57:45 [INFO] [2020-01-14 06:57:45,206 f5_cccl.resource.resource INFO] Updating ApiApplicationService: /service/default_iapp-tcp
2020/01/14 06:57:52 [WARNING] Overwriting existing entry for backend {ServiceName:nginxservice ServicePort:80 Namespace:default}
2020/01/14 06:57:52 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/01/14 06:57:52 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/01/14 06:57:52 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/01/14 06:57:52 [WARNING] Overwriting existing entry for backend {ServiceName:nginxservice ServicePort:80 Namespace:default}
2020/01/14 06:57:52 [INFO] Wrote 0 Virtual Server and 1 IApp configs
#####################################################
##########here is my services and pods ####################
root@ubuntu:~/iapp/iapp_new/iapp_latest/new_tcp_and# kubectl get pods -o wide
NAME                             READY   STATUS    RESTARTS   AGE     IP            NODE         NOMINATED NODE   READINESS GATES
nginx-test-5c5d7b7b68-48b8c      1/1     Running   0          6d15h   10.244.1.52   worknode34   <none>           <none>
nginx-test-5c5d7b7b68-sgsj7      1/1     Running   0          14d     10.244.1.45   worknode34   <none>           <none>
nginx-test2-5c5d7b7b68-5pg9q     1/1     Running   0          7d16h   10.244.0.37   ubuntu       <none>           <none>
nginx-test2-5c5d7b7b68-bcxfx     1/1     Running   0          6d15h   10.244.0.39   ubuntu       <none>           <none>
nginxservice3-685dd9ddd4-j2jzx   1/1     Running   0          15d     10.244.0.34   ubuntu       <none>           <none>
nginxservice3-685dd9ddd4-mmtxc   1/1     Running   0          15d     10.244.1.42   worknode34   <none>           <none>
root@ubuntu:~/iapp/iapp_new/iapp_latest/new_tcp_and# kubectl get svc
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes      ClusterIP   10.96.0.1       <none>        443/TCP   150d
nginxservice    ClusterIP   10.97.14.7      <none>        80/TCP    110d
nginxservice3   ClusterIP   10.107.66.233   <none>        80/TCP    25d
##############################################
##########here is my configmap-yaml##############
root@ubuntu:~/iapp/iapp_new/iapp_latest/new_tcp_and# cat tcp.yaml 
kind: ConfigMap
apiVersion: v1
metadata:
  name: iapp-tcp
  namespace: default
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
   {
     "virtualServer": {
       "backend": {
         "serviceName": "nginxservice",
         "servicePort": 80
       },
       "frontend": {
         "partition": "service",
         "iapp": "/Common/iapp_tcp",
         "iappPoolMemberTable": {
           "name": "pool__members",
           "columns": [
               {"name": "addr", "kind": "IPAddress"},
               {"name": "port", "kind": "Port"},
               {"name": "connection_limit", "value": "0"}
           ]
         },
         "iappOptions": {
           "description": "iapp_tcp"
         },
         "iappVariables": {
           "pool__pool_to_use": "/#create_new#",
           "pool__addr": "192.168.1.132",
           "pool__port": "8081",
           "vs__SNATConfig": "10.244.2.20 10.244.2.21",
           "vs__ProfileTCP": "tcp idle-timeout 300",
           "vs__ProfileDefaultPersist": "source_addr",
           "pool_lb": "round-robin",
           "monitor__Monitors": "tcp_new send 'tcpdata' recv 'nginx' interval 10 timeout 31",
           "pool__irules": "when CLIENT_ACCEPTED { \r\n log local0. \"clientIP[IP::client_addr]\"\r\n} "
         }
       }
     }
   }
#############################################
############here is my iapp-tmpl################

cli admin-partitions {
    update-partition Common
}
sys application template /Common/iapp_tcp {
    actions {
        definition {
            html-help {
            }
            implementation {
                set app $tmsh::app_name


#create  pool
set poolmembers ""

foreach row $::pool__members {
    array set columns [lindex $row 0]
    set ip $columns(addr)
    set port $columns(port)
    append poolmembers "$ip:$port" " "
}

#monitor
if { $::monitor__Monitors eq "tcp_default" } {
   set monitorname  tcp
} elseif {$::monitor__Monitors contains "tcp_new"} {
   set monitorname  ${app}_monitor
   set monitordata [ string replace $::monitor__Monitors 0 6 ]
   tmsh::create ltm monitor tcp ${monitorname} ${monitordata}
} elseif { $::monitor__Monitors eq "http_default" } {
   set monitorname  http
} elseif { $::monitor__Monitors contains "http_new" } {
   set monitorname  ${app}_monitor
   set monitordata [ string replace $::monitor__Monitors 0 7 ]
   tmsh::create ltm monitor udp ${monitorname} ${monitordata}
}

set poolname ${app}_pool
tmsh::create ltm pool ${poolname} members add \{ ${poolmembers} \} monitor ${monitorname}  load-balancing-mode $::pool_lb

#snat
if { $::vs__SNATConfig  eq "automap" } {
   set snatact $::vs__SNATConfig
} else { 
   set snatpool ${app}_snatpool
   tmsh::create ltm snatpool ${snatpool} members add \{ $::vs__SNATConfig \} 
   set snatact "snat pool ${snatpool} "
}

#tcp profile
if { $::vs__ProfileTCP eq "tcp"  } {
   set tcpprofile tcp
} elseif { $::vs__ProfileTCP contains "idle-timeout" } {
  set idletimeout [ string replace $::vs__ProfileTCP 0 3 ]
  set tcpprofile ${app}_tcpprofile
  tmsh::create ltm profile tcp ${tcpprofile} ${idletimeout}
}

#irule
if { $::pool__irules eq "none" } {
   set ruleact $::pool__irules
} else { 
  set irulesname ${app}_irule
  tmsh::create ltm rule ${irulesname} $::pool__irules
  set ruleact "{${irulesname}}"
}

#persis
if {  $::vs__ProfileDefaultPersist eq "none"  }  {
     set persisact $::vs__ProfileDefaultPersist
} elseif {  $::vs__ProfileDefaultPersist eq "source_addr"  } {
     set persisname $::vs__ProfileDefaultPersist
     set persisact "replace-all-with { ${persisname} }"
} elseif {  $::vs__ProfileDefaultPersist contains  "source_addr" and $::vs__ProfileDefaultPersist contains "timeout" } {
     set timeout [ string replace $::vs__ProfileDefaultPersist 0 11 ]
     set persisname ${app}_persis
     tmsh::create ltm persistence source-addr ${persisname}  ${timeout}
     set persisact "replace-all-with { ${persisname} }"
}

#create  VS
set vsname ${app}_vs
tmsh::create ltm virtual ${vsname} destination $::pool__addr:$pool__port profiles add \{ ${tcpprofile} \} pool ${poolname} ip-protocol tcp  rules ${ruleact} source-address-translation \{ type ${snatact} \}  persist  ${persisact} 
            }
            macro {
            }
            presentation {
            }
            role-acl none
            run-as none
        }
    }
    description none
    ignore-verification false
    requires-bigip-version-max none
    requires-bigip-version-min none
    requires-modules { ltm }
    signing-key none
    tmpl-checksum none
    tmpl-signature none
}
#################here is my F5 info
root@(f5k8s)(cfg-sync Standalone)(Active)(/Common)(tmos)# list net self
net self out {
    address 192.168.1.50/24
    allow-service all
    traffic-group traffic-group-local-only
    vlan out
}
net self 10.244.2.3 {
    address 10.244.2.3/16
    traffic-group traffic-group-local-only
    vlan flannel_vxlan
}
net self self9 {
    address 192.168.19.20/24
    allow-service {
        default
    }
    traffic-group traffic-group-local-only
    vlan vlan9
}
net self self5 {
    address 192.168.5.100/24
    allow-service {
        default
    }
    traffic-group traffic-group-local-only
    vlan vlan5
}
root@(f5k8s)(cfg-sync Standalone)(Active)(/Common)(tmos)# list net arp 
net arp /Common/k8s-10.244.0.37 {
    ip-address 10.244.0.37
    mac-address e6:06:b8:5b:f7:ea
}
net arp /Common/k8s-10.244.0.39 {
    ip-address 10.244.0.39
    mac-address e6:06:b8:5b:f7:ea
}
net arp /Common/k8s-10.244.1.45 {
    ip-address 10.244.1.45
    mac-address e6:4f:68:9a:05:80
}
net arp /Common/k8s-10.244.1.52 {
    ip-address 10.244.1.52
    mac-address e6:4f:68:9a:05:80
}
root@(f5k8s)(cfg-sync Standalone)(Active)(/Common)(tmos)# list net rou
Modules:
  routing                
Components:
  route                  route-domain           router-advertisement   
root@(f5k8s)(cfg-sync Standalone)(Active)(/Common)(tmos)# list net route
root@(f5k8s)(cfg-sync Standalone)(Active)(/Common)(tmos)# 
root@(f5k8s)(cfg-sync Standalone)(Active)(/Common)(tmos)# 
root@(f5k8s)(cfg-sync Standalone)(Active)(/Common)(tmos)# q
[root@f5k8s:Active:Standalone] config # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.1.10.1       0.0.0.0         UG    9      0        0 mgmt
10.1.10.0       0.0.0.0         255.255.255.0   U     0      0        0 mgmt
10.244.0.0      0.0.0.0         255.255.0.0     U     0      0        0 flannel_vxlan
127.1.1.0       0.0.0.0         255.255.255.0   U     0      0        0 tmm
127.7.0.0       127.1.1.253     255.255.0.0     UG    0      0        0 tmm
127.20.0.0      0.0.0.0         255.255.0.0     U     0      0        0 tmm_bp
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 out
192.168.5.0     0.0.0.0         255.255.255.0   U     0      0        0 vlan5
192.168.19.0    0.0.0.0         255.255.255.0   U     0      0        0 vlan9

**Comment by mdditt2000** [comment] 2020-05-14 18:22
Issue has being resolved in CIS 2.0. Please note that CIS 2.0 will use AS3 agent by default

**Comment by mdditt2000** [comment] 2020-05-26 18:08
Resolved in CIS 2.0

**Closed by mdditt2000** 2020-05-26 18:08 UTC
Labels: Awaiting response
