### ISSUE TITLE
How to deploy this with F5 as openstack lbaas v2

### ISSUE THREAD

**Issue by jenningsloy318** [F5Networks/k8s-bigip-ctlr#1031] opened 2019-09-27 07:04 UTC
we deploy our kubernets on a openstack with F5 as Lbaas v2,  not sure if we can deploy this controller to our environment . 

as from F5 websites, we know that F5 don't support Octavia api, so not sure how to ultilize F5 as our ingress controller.

**Comment by jgruber** [comment] 2019-09-30 20:33
If you have running f5-openstack-agent(s) to provision a BIG-IP (standalone or cluster) as a provider for Neturon LBaaSv2, that integration is completely separate from K8s Ingress controller provisioning of BIG-IPs. The OpenStack community defined the LBaaSv2 infrastructure API, the K8s community defined the Ingress infrastructure API. They are different designs with very different objectives. They are not unified by either community.

The Neutron v2 LBaaS API supports populating LBaaS pool members as Neutron fixed_ips (associated with specific Neutron ports) or simply IP address, which are assumed routable from the provider (in your case F5 BIG-IPs) devices. The Neutron LBaaSv2 VIP IP is required to be associated with a Neutron port by design. The f5-openstack-agent, unlike the community reference implementation for either LBaaSv2 or Octavia devices, provisions TMOS devices which are always multi-tenant. The multi-tenant BIG-IP devices used for LBaaSv2 can be provisioned such that they are intended to be cloud-edge devices (on provider networks) where pool members are assumed L3 routable (typically Floating IPs), called global-routing-mode, or they can be configured to dynamically provision L2+L3 interfaces on the BIG-IP devices, getting appropriate resources (ports and fixed_ips) from Neutron.

Depending on how you setup your K8s cluster on OpenStack, how the VIP and pool members are managed via a K8s Ingress controller could work on the same BIG-IP cluster, but you must be certain there are no provisioning conflicts. Be aware that the Neutron LBaaSv2 integration and the k8s-bigip-ctlr were not designed to target the same TMOS devices, thus they do not assure that no configuration conflicts exist. There is no test coverage where Neutron LBaaSv2 and K8s Ingress are tested together in any way.

In TMOS (BIG-IP platform) VLAN IDs, VxLAN VNIs, GRE tunnel IDs, and route-domain IDs (ids for routing tables) are global to the TMOS devices. They must not conflict between orchestrations.

f5-openstack-agent provisions BIG-IP such that all objects are created in a TMOS configuration partition corresponding to the OpenStack tenant id requesting LBaaSv2 services. Depending on if you expect the f5-openstack-agent to provision L2+L3 objects on TMOS, then conflicts with route domains can also be an issue.

K8s controller also uses partitions, but they are not tied to OpenStack tenant ids.

**Comment by mdditt2000** [comment] 2019-10-01 21:23
@jgruber thank you for your explanation. @jenningsloy318 does this response answer your question?

**Comment by jenningsloy318** [comment] 2019-10-02 00:19
I clearly understood, as our cloud platform use F5as lb,but currently F5 don’t have octavia api driver ,only support legacy neutron lbaas v2api driver so current it not very convenient to directly use platform lb feature which integrated with k8s

**Comment by mdditt2000** [comment] 2019-10-02 17:29
@jenningsloy318 totally understand. We have moved a declarative API called AS3 which is now integrated into BIGIP. If you install AS3 on BIGIP you should be able to configure services via a API call. This is way more advanced than LBAAS and extended services definitions. CIS can also communicate to BIGIP via AS3. As long as the internal vlan on bigip is part of the K8s cluster things will work. My recommendation would be to use calico or nodeport.

**Comment by jenningsloy318** [comment] 2019-10-05 23:58
@mdditt2000 thanks for your clarification,I wonder if there is a reference project that use AS3 and integrated openstack and kubernetes together?

**Comment by mdditt2000** [comment] 2020-05-29 12:43
Closing this issue out. Questions answered.

**Closed by mdditt2000** 2020-05-29 12:43 UTC
