### ISSUE TITLE
k8s-bigip-ctlr restart leads to application downtime

### ISSUE THREAD

**Issue by anjkl** [F5Networks/k8s-bigip-ctlr#1240] opened 2020-04-17 13:01 UTC
#### Description

A restart of pod k8s-bigip-ctlr leads to downtime for applications created using iApps templates.

*Steps to reproduce*:
* Create ConfigMap for the controller as I provided below.
* Run ping to IP of your application (`ping y.y.y.y -O | perl -lne 'print scalar(localtime), ": ", $_'`)
* Delete Pod of the controller (`kubectl -n f5-bigip delete po  k8s-bigip-ctlr-deployment-xxxxx`)
* Check log and lost packets. You have to see that some packets were lost and iApp was deleted and created again.

*Expected behavior/Desired behavior*: restarts of k8s-bigip-ctlr just update iApps instead of deleting and creating them from scratch. It shouldn't lead to application downtime.

#### Kubernetes Version
1.14.6, v1.16.7

#### Controller Version
at least 1.9.0 to 1.14.0

#### BIG-IP Version
13.1.1.2

#### Diagnostic Information
k8s-bigip-ctlr run args:
```
Annotations:        <none>
Status:             Running
IP:                 x.x.y.z
Controlled By:      ReplicaSet/k8s-bigip-ctlr-deployment-55d8bbcc5
Containers:
  k8s-bigip-ctlr:
    Container ID:  docker://e90bcb33ae80d5b071626629668cadc62fb32370392b47e2c24de435f8fc553a
    Image:         docker-hub.proxy.local/f5networks/k8s-bigip-ctlr:1.14.0
    Image ID:      docker-pullable://docker-hub.proxy.local/f5networks/k8s-bigip-ctlr@sha256:25bdfc947ed4cdd172a68e37c51dbaa8ca87fcbc4d894622b42a260755a2bf68
    Port:          8080/TCP
    Host Port:     8080/TCP
    Command:
      /app/bin/k8s-bigip-ctlr
    Args:
      --credentials-directory=/credentials-directory
      --bigip-partition=SANDBOX_K8S
      --pool-member-type=cluster
      --namespace-label=bigip
      --log-level=INFO
...
```

Tested F5 ConfigMap description:
```
Name:         f5-coredns
Namespace:    external-dns
Labels:       f5type=virtual-server
Annotations:  

Data
====
data:
----
{
  "virtualServer": {
    "backend": {
      "serviceName": "coredns",
      "servicePort": 53
    },
    "frontend": {
      "partition": "SANDBOX_K8S",
      "iapp": "/Common/f5.dns",
      "iappPoolMemberTable": {
        "name": "vs_pool__members",
        "columns": [
            {"name": "addr", "kind": "IPAddress"},
            {"name": "port", "kind": "Port"}
        ]
      },
      "iappOptions": {
        "description": "k8s dns servers"
      },
      "iappVariables": {
        "basic__advanced": "yes",
        "basic__display_help": "max",
        "client_opt__tcp_wan_opt": "/#create_new#",
        "server_opt__tcp_lan_opt": "/#create_new#",
        "net__client_mode": "wan",
        "net__client_vlan": "/Common/VL_1111",
        "net__route_to_bigip": "no",
        "net__same_subnet": "no",
        "net__server_mode": "lan",
        "net__snat_type": "automap",
        "irules__irules_udp": " ",
        "irules__irules_tcp": " ",
        "vs_pool__slow_ramp_setvalue": "300",
        "vs_pool__tcp_req_queueing": "no",
        "vs_pool__use_pga": "no",
        "vs_pool__use_slow_ramp": "yes",
        "vs_pool__vs_addr": "y.y.y.y",
        "vs_pool__vs_port": "53",
        "vs_pool__lb_method_choice": "round-robin",
        "vs_pool__pool_to_use": "/#create_new#",
        "app_health__monitor": "/#create_new#",
        "app_health__record_type": "a",
        "app_health__frequency": "5",
        "app_health__send": "kubernetes.default.svc.external.zone",
        "app_health__recv": "x.x.x.x"
      }
    }
  }
}

schema:
----
f5schemadb://bigip-virtual-server_v0.1.7.json
Events:  <none>
```

k8s-bigip-ctlr logs during starting up:
```
...
2020/04/17 11:37:24 [INFO] NodePoller started: (0xc000d3c3f0)
2020/04/17 11:37:24 [INFO] ProcessNodeUpdate: Change in Node state detected
2020/04/17 11:37:24 [INFO] Registered BigIP Metrics
2020/04/17 11:37:24 [INFO] Watching Ingress resources.
2020/04/17 11:37:24 [INFO] Watching ConfigMap resources.
2020/04/17 11:37:24 [INFO] Handling ConfigMap resource events.
2020/04/17 11:37:24 [INFO] Handling Ingress resource events.
2020/04/17 11:37:24 [INFO] Watching Ingress resources.
2020/04/17 11:37:24 [INFO] Watching ConfigMap resources.
2020/04/17 11:37:24 [INFO] Handling ConfigMap resource events.
2020/04/17 11:37:24 [INFO] Handling Ingress resource events.
2020/04/17 11:37:24 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/04/17 11:37:24 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2020/04/17 11:37:24 [WARNING] Overwriting existing entry for backend {ServiceName:coredns ServicePort:53 Namespace:external-dns}
2020/04/17 11:37:24 [INFO] [2020-04-17 11:37:24,490 f5_cccl.resource.resource INFO] Deleting IcrApplicationService: /SANDBOX_K8S/external-dns_f5-coredns
2020/04/17 11:37:24 [INFO] [2020-04-17 11:37:24,676 f5_cccl.resource.resource INFO] Deleting IcrNode: /SANDBOX_K8S/x.x.x.y
2020/04/17 11:37:24 [INFO] [2020-04-17 11:37:24,746 f5_cccl.resource.resource INFO] Deleting IcrNode: /SANDBOX_K8S/x.x.x.z
2020/04/17 11:37:33 [INFO] [2020-04-17 11:37:33,785 f5_cccl.resource.resource INFO] Creating ApiApplicationService: /SANDBOX_K8S/external-dns_f5-coredns
```

ping log to IP of Virtual Server:
```
~ ping y.y.y.y -O | perl -lne 'print scalar(localtime), ": ", $_'
Fri Apr 17 11:37:21 2020: 64 bytes from y.y.y.y: icmp_seq=58 ttl=254 time=0.147 ms
Fri Apr 17 11:37:22 2020: 64 bytes from y.y.y.y: icmp_seq=59 ttl=254 time=0.138 ms
Fri Apr 17 11:37:23 2020: 64 bytes from y.y.y.y: icmp_seq=60 ttl=254 time=0.155 ms
Fri Apr 17 11:37:24 2020: 64 bytes from y.y.y.y: icmp_seq=61 ttl=254 time=0.122 ms
Fri Apr 17 11:37:26 2020: no answer yet for icmp_seq=62
Fri Apr 17 11:37:27 2020: no answer yet for icmp_seq=63
Fri Apr 17 11:37:28 2020: no answer yet for icmp_seq=64
Fri Apr 17 11:37:29 2020: no answer yet for icmp_seq=65
Fri Apr 17 11:37:30 2020: no answer yet for icmp_seq=66
Fri Apr 17 11:37:31 2020: no answer yet for icmp_seq=67
Fri Apr 17 11:37:32 2020: no answer yet for icmp_seq=68
Fri Apr 17 11:37:33 2020: no answer yet for icmp_seq=69
Fri Apr 17 11:37:34 2020: no answer yet for icmp_seq=70
Fri Apr 17 11:37:34 2020: 64 bytes from y.y.y.y: icmp_seq=71 ttl=254 time=0.153 ms
Fri Apr 17 11:37:35 2020: 64 bytes from y.y.y.y: icmp_seq=72 ttl=254 time=0.181 ms
Fri Apr 17 11:37:36 2020: 64 bytes from y.y.y.y: icmp_seq=73 ttl=254 time=0.158 ms
```

**Comment by trinaths** [comment] 2020-04-19 08:01
contact @mdditt2000 to work with you to migrate from iApps templates to AS3 userdefined configMaps.

**Comment by mdditt2000** [comment] 2020-05-14 18:27
@anjkl we need to start looking at migrating off iApps to a user-defined configmap or CRD. CIS 2.0 will introduce support for CRDs. Also CIS 2.0 will use AS3 by default. Moving forward their wont be fixes or changes using iApps on CCCL.

**Comment by veeramalla-f5** [comment] 2020-08-19 19:40
@anjkl I tried to reproduce the issue. I do not see any issue. 

CIS/CC does not create/update or delete any resources once restart
2020/08/19 19:32:13 [DEBUG] [2020-08-19 19:32:13,879 f5_cccl.service.manager DEBUG] Creating 0 resources...
2020/08/19 19:32:13 [DEBUG] [2020-08-19 19:32:13,879 f5_cccl.service.manager DEBUG] Updating 0 resources...
2020/08/19 19:32:13 [DEBUG] [2020-08-19 19:32:13,879 f5_cccl.service.manager DEBUG] Deleting 0 resources...


LTM Log(Nothing created, Updated or deleted)
Aug 19 12:21:10 localhost err mcpd[7566]: 01020037:3: The requested folder (/Common/appsvcs) already exists.

Audit Log(Nothing created, Updated or deleted)
Aug 19 12:21:10 localhost notice icrd_child[14703]: 01420002:5: AUDIT - pid=14703 user=admin folder=/Common module=(tmos)# status=[01020037:3: The requested folder (/Common/appsvcs) already exists.] cmd_data=create sys folder appsvcs


Can you share similar logs from your end. 

steps:
```
restart controller[Enable Debug]
filter out the logs as shown above
please share ltm and audit logs at the time of restart
```

**Comment by anjkl** [comment] 2020-08-25 12:17
I tried to reproduce the issue using the latest version (2.1.0) of the controller. It was run with the following parameters:

    - --credentials-directory=/credentials-directory
    - --bigip-partition=SANDBOX_K8S
    - --pool-member-type=cluster
    - --namespace-label=bigip
    - --log-level=DEBUG
    - --insecure=true
    - --agent=cccl


Similar logs that you provided:

    2020/08/25 09:24:04 [DEBUG] [2020-08-25 09:24:04,638 f5_cccl.service.manager DEBUG] Removing legacy resources...
    2020/08/25 09:24:04 [DEBUG] [2020-08-25 09:24:04,639 f5_cccl.service.manager DEBUG] Deleting 3 resources...
    2020/08/25 09:25:11 [DEBUG] [2020-08-25 09:25:11,635 f5_cccl.service.manager DEBUG] Creating 1 resources...
    2020/08/25 09:25:14 [DEBUG] [2020-08-25 09:25:14,950 f5_cccl.service.manager DEBUG] Updating 0 resources...
    2020/08/25 09:25:14 [DEBUG] [2020-08-25 09:25:14,950 f5_cccl.service.manager DEBUG] Deleting 0 resources...


Ping log:

    Tue Aug 25 09:24:11 2020: 64 bytes from 10.96.12.253: icmp_seq=201 ttl=251 time=106.705 ms
    Tue Aug 25 09:24:13 2020: 64 bytes from 10.96.12.253: icmp_seq=203 ttl=251 time=81.925 ms
    Tue Aug 25 09:24:14 2020: 64 bytes from 10.96.12.253: icmp_seq=204 ttl=251 time=89.946 ms
    Tue Aug 25 09:24:15 2020: Request timeout for icmp_seq 205
    Tue Aug 25 09:24:16 2020: Request timeout for icmp_seq 206
    .....
    .....
    .....
    Tue Aug 25 09:25:14 2020: Request timeout for icmp_seq 263
    Tue Aug 25 09:25:15 2020: Request timeout for icmp_seq 264
    Tue Aug 25 09:25:15 2020: 64 bytes from 10.96.12.253: icmp_seq=265 ttl=251 time=139.658 ms
    Tue Aug 25 09:25:16 2020: 64 bytes from 10.96.12.253: icmp_seq=266 ttl=251 time=91.598 ms
    Tue Aug 25 09:25:17 2020: 64 bytes from 10.96.12.253: icmp_seq=267 ttl=251 time=367.980 ms


audit log:

    Aug 25 09:24:14 slot1/lb01 notice mcpd[13170]: 01070417:5: AUDIT - client tmsh, tmsh-pid-11451, user user - transaction #3562704014-2 - object 0 - obj_delete { app_instance { app_instance_name "/SANDBOX_K8S/external-dns_f5-coredns.app/external-dns_f5-coredns" } } [Status=Command OK]
    Aug 25 09:24:14 slot1/lb01 notice icrd_child[11451]: 01420002:5: AUDIT - pid=11451 user=user folder=/Common module=(tmos)# status=[Command OK] cmd_data=delete sys application service /SANDBOX_K8S/external-dns_f5-coredns.app/external-dns_f5-coredns


I haven't found any information related to removing the iApp in ltm log.

**Comment by mdditt2000** [comment] 2020-09-21 20:27
Create internal Jira item CONTCNTR-2148 - Need to get test to try recreate this issue. @anjkl are you using the defaul "iapp": "/Common/f5.dns", or have you made any modifications to the iApp?

**Comment by anjkl** [comment] 2020-09-22 07:06
We use the default iApp template /Common/f5.dns without any modifications.

**Comment by mdditt2000** [comment] 2020-09-28 15:22
**Please note:** SR takes high prescience due to SLA. Team is looking at the SR and not this Github issue. SR is 1-6713461651

**Comment by mdditt2000** [comment] 2020-09-29 18:00
**Quick update**. Dev team **can reproduce the issue.** with the DNS iAPP. I have assigned the issue to a developer for resolution. I will have more information after standup today. Thanks

**Comment by mdditt2000** [comment] 2020-10-21 20:07
At this time no hotfix is required. DNS CRD is going to be developed. The DNS CRD design work begins in the sprint 51 starting tomorrow.

**Comment by mdditt2000** [comment] 2020-10-28 18:28
I am the owner of the Service Request C3362299. @anjkl please review the email i sent you via the SR regarding the work we are doing with DNS CRDs. Would like to get your feedback. 

Since i am prioritizing the SR, this Github issue is duplicate. I am going to add it to the milestone for 2.2.1 and close with the new release.

**Comment by mdditt2000** [comment] 2020-11-04 21:01
Thank you for the update. I have created a Story for Dev to pickup this sprint. Sprint started yesterday,

Internal PM Jira CONTCNTR-2234 - Hotfix on CIS 1.14 prevent CIS CCCL from removing the virtual when CIS is restarted. We can reproduce the issue internally. Once i have information regarding the fix i will share. I am going to update the Github repo as well.

**Comment by mdditt2000** [comment] 2020-11-09 20:41
Testing and regression pending. Image should be available this week if everything passes

**Comment by mdditt2000** [comment] 2020-11-10 17:26
Hotfix has been provided via SR. Issue is ready to be closed out.

**Comment by mdditt2000** [comment] 2020-11-19 17:18
Hotfix fixed the issue. Closing issue

**Closed by mdditt2000** 2020-11-19 17:18 UTC
Labels: bug, ready to close, resolved, service request
