### ISSUE TITLE
More Load Balance Method Support both in TransportServer and VirtualServer

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2304] opened 2022-03-18 02:27 UTC
Current the VirtualServer can only support one Load Balance Method *Round Robin*, and also there no option to set the Load Balance Method in pool.

The native k8s kube-proxy with iptables support 2 LB methods, and the native k8s kube-proxy with IPVS  support 6 LB methods, Cause BIG-IP support bunch of LB methods, could CIS implement a enhance in this approach?

**Comment by sectoreleven** [comment] 2022-03-28 19:51
My company has identified this requirement as well, as we use least-connections-member as our organization standard. We would upvote for this if we could.

**Comment by trinaths** [comment] 2022-03-30 12:12
Created [CONTCNTR-3249] for internal tracking.

**Comment by trinaths** [comment] 2022-03-30 18:15
Closing this issue. Duplicate of https://github.com/F5Networks/k8s-bigip-ctlr/issues/2224

**Closed by trinaths** 2022-03-30 18:15 UTC
Labels: feature-request, untriaged
