### ISSUE TITLE
Extra logging with white listed virtual servers

### ISSUE THREAD

**Issue by kmunson1973** [F5Networks/k8s-bigip-ctlr#698] opened 2018-05-18 15:24 UTC
#### Description
When you create a virtual server with the whitelist metadata erroneous error logs appear:
2018/05/18 15:19:47 [ERROR] [2018-05-18 15:19:47,021 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.214.254.13:443/mgmt/tm/ltm/virtual-address/~k8s~10.214.2.205/
2018/05/18 15:19:47 [INFO] Text: u'{"code":400,"message":"01070344:3: Cannot delete referenced virtual address /k8s/10.214.2.205.","errorStack":[],"apiError":3}'
2018/05/18 15:19:47 [ERROR] [2018-05-18 15:19:47,022 f5_cccl.service.manager ERROR] Resource /k8s/10.214.2.205 delete error, requeuing task...
2018/05/18 15:19:47 [INFO] [2018-05-18 15:19:47,022 f5_cccl.resource.resource INFO] Deleting IcrVirtualAddress: /k8s/10.214.2.206
2018/05/18 15:19:47 [ERROR] [2018-05-18 15:19:47,088 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrVirtualAddress) /k8s/10.214.2.206.
2018/05/18 15:19:47 [ERROR] [2018-05-18 15:19:47,089 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.214.254.13:443/mgmt/tm/ltm/virtual-address/~k8s~10.214.2.206/
2018/05/18 15:19:47 [INFO] Text: u'{"code":400,"message":"01070344:3: Cannot delete referenced virtual address /k8s/10.214.2.206.","errorStack":[],"apiError":3}'
2018/05/18 15:19:47 [ERROR] [2018-05-18 15:19:47,089 f5_cccl.service.manager ERROR] Resource /k8s/10.214.2.206 delete error, requeuing task...
2018/05/18 15:19:51 [INFO] [2018-05-18 15:19:51,570 f5_cccl.resource.resource INFO] Deleting IcrVirtualAddress: /k8s/10.214.2.205
2018/05/18 15:19:51 [ERROR] [2018-05-18 15:19:51,658 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrVirtualAddress) /k8s/10.214.2.205.
2018/05/18 15:19:51 [ERROR] [2018-05-18 15:19:51,658 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.214.254.13:443/mgmt/tm/ltm/virtual-address/~k8s~10.214.2.205/
2018/05/18 15:19:51 [INFO] Text: u'{"code":400,"message":"01070344:3: Cannot delete referenced virtual address /k8s/10.214.2.205.","errorStack":[],"apiError":3}'
2018/05/18 15:19:51 [ERROR] [2018-05-18 15:19:51,658 f5_cccl.service.manager ERROR] Resource /k8s/10.214.2.205 delete error, requeuing task...
2018/05/18 15:19:51 [INFO] [2018-05-18 15:19:51,658 f5_cccl.resource.resource INFO] Deleting IcrVirtualAddress: /k8s/10.214.2.206
2018/05/18 15:19:51 [ERROR] [2018-05-18 15:19:51,726 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrVirtualAddress) /k8s/10.214.2.206.
2018/05/18 15:19:51 [ERROR] [2018-05-18 15:19:51,726 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.214.254.13:443/mgmt/tm/ltm/virtual-address/~k8s~10.214.2.206/
2018/05/18 15:19:51 [INFO] Text: u'{"code":400,"message":"01070344:3: Cannot delete referenced virtual address /k8s/10.214.2.206.","errorStack":[],"apiError":3}'
2018/05/18 15:19:51 [ERROR] [2018-05-18 15:19:51,727 f5_cccl.service.manager ERROR] Resource /k8s/10.214.2.206 delete error, requeuing task...

#### Kubernetes Version
OCP 3.9

#### Controller Version
1.5

#### BIG-IP Version
13.1

**Comment by russokj** [comment] 2018-05-18 21:00
We originally had documentation which mentioned the virtual address created by the whitelisted virtual server would also have to be manually whitelisted.  We removed that step because our testing seemed to indicate it wasn't necessary (or maybe because we made a change that no longer required it). You can attempt to do that while we figure out why we thought it was no longer needed (i.e., bad assumption on our part, or an issue with the reconciliation code itself).

Can you explain your setup a little more.  Do you have only white listed virtuals, or a combination of whitelisted/non-whitelisted?

**Comment by tylfin** [comment] 2019-01-24 12:51
@russokj Any movement on this issue? Getting the same errors latest controller

**Comment by vincentmli** [comment] 2019-01-31 21:56
@tylfin could you let me know how I deploy whitelisted virtual through the controller so maybe I can reproduce the issue?

**Comment by rsalsa** [comment] 2019-02-15 00:19
@vincentmli you need to modify the virtual via tmsh to add the following:

`modify ltm virtual <name> metadata add { cccl-whitelist { value 1 } }`

It's still reproducible with the last version.

**Comment by rsalsa** [comment] 2019-02-15 00:28
Debug level output: 

[DEBUG] [2019-02-15 00:24:48,212 f5_cccl.resource.resource DEBUG] Resource test-l4 cccl-whitelist: True
[DEBUG] [2019-02-15 00:24:48,213 f5_cccl.resource.resource DEBUG] Resource test-l4 cccl-whitelist: True
[DEBUG] [2019-02-15 00:24:48,214 f5_cccl.bigip DEBUG] BIG-IP ltm refresh took 0.20699 seconds.
[DEBUG] [2019-02-15 00:24:48,214 f5_cccl.service.manager DEBUG] Post-process nodes.
[DEBUG] [2019-02-15 00:24:48,214 f5_cccl.service.manager DEBUG] Updating 0 resources...
[DEBUG] [2019-02-15 00:24:48,214 f5_cccl.service.manager DEBUG] Deleting 0 resources...
[DEBUG] [2019-02-15 00:24:48,214 f5_cccl.service.manager DEBUG] Remove superfluous virtual addresses.
[DEBUG] [2019-02-15 00:24:48,214 f5_cccl.service.manager DEBUG] Deleting 1 resources...
[INFO] [2019-02-15 00:24:48,215 f5_cccl.resource.resource INFO] Deleting IcrVirtualAddress: /k8s/0.0.0.0
[DEBUG] [2019-02-15 00:24:48,215 root DEBUG] get WITH uri: https://10.0.1.155:443/mgmt/tm/ltm/virtual-address/~k8s~0.0.0.0 AND suffix:  AND kwargs: {}
[DEBUG] [2019-02-15 00:24:48,237 requests.packages.urllib3.connectionpool DEBUG] "GET /mgmt/tm/ltm/virtual-address/~k8s~0.0.0.0 HTTP/1.1" 200 633
[DEBUG] [2019-02-15 00:24:48,239 root DEBUG] delete WITH uri: https://10.0.1.155:443/mgmt/tm/ltm/virtual-address/~k8s~0.0.0.0/ AND suffix:  AND kwargs: {}
[DEBUG] [2019-02-15 00:24:48,277 requests.packages.urllib3.connectionpool DEBUG] "DELETE /mgmt/tm/ltm/virtual-address/~k8s~0.0.0.0/ HTTP/1.1" 400 120
[ERROR] [2019-02-15 00:24:48,278 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrVirtualAddress) /k8s/0.0.0.0.
[ERROR] [2019-02-15 00:24:48,278 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.0.1.155:443/mgmt/tm/ltm/virtual-address/~k8s~0.0.0.0/
[INFO] Text: u'{"code":400,"message":"01070344:3: Cannot delete referenced virtual address /k8s/0.0.0.0.","errorStack":[],"apiError":3}'
[ERROR] [2019-02-15 00:24:48,278 f5_cccl.service.manager ERROR] Resource /k8s/0.0.0.0 delete error, requeuing task...

**Comment by rsalsa** [comment] 2019-02-15 00:29
The following is in the ltm logs on the BIG-IP:

`err mcpd[6817]: 01070344:3: Cannot delete referenced virtual address /k8s/0.0.0.0.`

**Comment by mdditt2000** [comment] 2020-02-06 21:18
CCCL based api has being removed in CIS 2.0. Moving to AS3 declarative API doesn't changes the behavior of whitelisting. Added AS3 override to add global configuration. Closing this issue out.

**Closed by mdditt2000** 2020-02-06 21:18 UTC
Labels: P3, help wanted
