### ISSUE TITLE
Enhancement: add cookie persistent 

### ISSUE THREAD

**Issue by luruiqiang** [F5Networks/k8s-bigip-ctlr#940] opened 2019-06-12 15:46 UTC
#### Description
My customer want to create cookie persistent by using configmap/ingress without iapp and as3.
They think iapp or as3 is complex. If we can use cookie persistent in configmap, it will meet most of needs 

#### Kubernetes Version
1.13

#### Controller Version
1.9.1

#### BIG-IP Version
v12.1

**Comment by mdditt2000** [comment] 2019-06-12 19:28
@luruiqiang cookie persistence is created by default using a cfgmap with AS3. AS3 will abstract all persistence option available on BigIP via a simple change in the declaration. 

Here is a example declaration that will provide what you need today from Kubernetes. https://raw.githubusercontent.com/mdditt2000/kubernetes/dev/cis-1-9/as3%20declaration/http.yaml

In CIS 1.11 we are taking a kubernetes ingress and converting to a declarative API for BigIP. This will be done via the AS3 toolchain allowing defaults to be configured such as cookie etc. CIS 1.10 is handling OpenShift Routes and CIS 1.10 will focus on ingress. Aprox timeline around 3 months. Please use the example provide today and more to ingress when CIS 1.11 ships. I can provide a demo for your customer etc. Let me know know.

**Comment by luruiqiang** [comment] 2019-06-17 03:47
Yes, we can use AS3 to create cookie persistence. but, there are some limits with AS3(https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html). My customer can't accept "Static ARP entries remain after deleting an AS3 ConfigMap."

**Comment by mdditt2000** [comment] 2019-06-17 06:48
Let me do some additional testing tomorrow. Your customer using Nodeport or cluster mode? The arp are not getting updated via AS3. The ARP should be removed based on the nodes in the pool. Will test tomorrow and get back to you. Thanks Mark

**Comment by mdditt2000** [comment] 2019-06-17 17:59
@luruiqiang tested AS3 declaration using CIS 1.9.1 and the static arp entries are getting removed correctly to reflect the correct "ip, node, mac" state. The ARP wont get removed if you simple delete the cfgmap. Since you are using a declarative API you need to declare state change in the declaration. For example remove the service and CIS will update the bigip. Service and all associated objects will be removed. Please use the  kubectl **apply** -f f5-as3-configmap.yaml. I can demonstrate this you would like to setup a call. 

**Note:** Only once you have no services in the declaration, you can delete the AS3 ConfigMap

**Comment by mdditt2000** [comment] 2019-06-17 18:58
Improve documentation https://jira.pdsea.f5net.com/browse/CONTCNTR-833

**Comment by mdditt2000** [comment] 2019-06-19 18:34
Did some additional testing. Static ARP address only remain if all services are getting removed. If you are applying an update you will see the expected behavior. For example you have a declaration with 2 applications called A1 + A2. You remove A2 by updating the AS3 declaration. A2 static arp will be removed. If you send a blank declaration to remove A1 then A1 static arp entries for the nodes will still remain. 

1. Send blank configMap
2. Delete configMap
3. Delete or restart the controller

We are in this weird state due to AS3 not having the capabilities to create or remove ARP request. Most likely a fix with DO.

**Comment by mdditt2000** [comment] 2019-06-20 17:25
Updated documentation https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-as3-delete-configmap.html. Please use #cc-kubernetes on f5cloudsolutions.slack.com

 cookie persistent by using configmap/ingress is coming in CIS 1.11 by default. CIS will create a AS3 declaration which by default will support persistence. Closing issue out.

**Closed by mdditt2000** 2019-06-20 17:25 UTC
Labels: 1.11, documentation
