### ISSUE TITLE
Hostless VS doesn't appear to work with IPAM

### ISSUE THREAD

**Issue by mwardbopp** [F5Networks/k8s-bigip-ctlr#2778] opened 2023-02-20 18:30 UTC
#### Setup Details
 CIS Version : 2.11.1
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.2
 AS3 Version: 3.41
 Agent Mode: AS3  
 Orchestration: K8S
 Orchestration Version:       
 Pool Mode: Nodeport      

#### Steps To Reproduce
configure virtualserver with no host and IPAM. It works when static virtualserveraddress is configured. IPAM works when host is set.
```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: l7-app2
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  policyName: app2-waf-policy
  virtualServerName: "l7-app2"
  ipamLabel: "prod"
  pools:
  - path: /
    service: nginx-plus
    servicePort: 80
```
#### Actual Result  
No configuration is sent to big-ip
2023/02/20 18:25:18 [ERROR] Hostless VS l7-app2 is configured with IPAM label: prod
2023/02/20 18:25:18 [DEBUG] IPAM Invalid IPAM Label:  for Virtual Server: nginx/l7-app2

**Comment by trinaths** [comment] 2023-02-24 09:17
@mwardbopp Unable to reproduce this issue. Please share more info to automation_toolchain_pm at f5 dot com.

**Comment by trinaths** [comment] 2023-02-28 15:08
@mwardbopp - Please share the required info

**Comment by trinaths** [comment] 2023-04-11 17:42
Created [CONTCNTR-3922] for internal tracking.

**Comment by vklohiya** [comment] 2023-06-14 05:05
Fixed with https://github.com/F5Networks/k8s-bigip-ctlr/pull/2917. Hence closing.

**Closed by vklohiya** 2023-06-14 05:05 UTC
Labels: bug, jira
