### ISSUE TITLE
Error log not clear when AS3 module missing from BIGIP

### ISSUE THREAD

**Issue by StevenBarre** [F5Networks/k8s-bigip-ctlr#1934] opened 2021-07-30 21:08 UTC
#### Setup Details
 CIS Version : 2.4.1
 Build: f5networks/k8s-bigip-ctlr:v2.4.1
 BIGIP Version: Big IP unknown
 AS3 Version: Not installed
 Agent Mode: AS3    
 Orchestration: OSCP
 Orchestration Version: 4.6
 Pool Mode: Cluster
 Additional Setup details: N/A

#### Description  
 
The error logs produced by the controller if the BIGIP doesn't have the AS3 package installed are cryptic and unhelpful

They should more clearly report the AS3 API endpoint is missing.

#### Steps To Reproduce
1) Run with `--as3`
2) Have BIGIP without AS3 installed
3) View error logs

#### Expected Result 

```
2021/07/28 18:14:11 [ERROR] AS3 API unavailable
```

#### Actual Result  

```
2021/07/28 18:14:11 [ERROR] Response body unmarshal failed: unexpected end of JSON input
2021/07/28 18:14:11 [ERROR] Internal Error
```

**Comment by walterk82** [comment] 2021-08-02 12:26
During start-up CIS should be able to perform a 404 check against the AS3 end-point and return a helpful error message.

**Comment by trinaths** [comment] 2021-08-05 08:44
@StevenBarre - When AS3 is missing in BIGIP, the below error is logged in CIS. Unable to reproduce the above logs. 

```
[centos@intent-llama-bastion ~]$ kk logs deploy/k8s-bigip-ctlr-deployment -f
2021/08/05 08:42:36 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.5.0, BuildInfo: azure-465-1952a80a2165b7fc2d3561795ad09d1eb8615136
2021/08/05 08:42:36 [DEBUG] Telemetry data reporting to TEEM server is disabled
2021/08/05 08:42:36 [DEBUG] [CCCL] ConfigWriter (0xc000570b70) writing section name global
2021/08/05 08:42:36 [INFO] ConfigWriter started: 0xc000570b70
2021/08/05 08:42:36 [DEBUG] [CCCL] ConfigWriter (0xc000570b70) successfully wrote section (global)
2021/08/05 08:42:36 [DEBUG] [CCCL] ConfigWriter (0xc000570b70) writing section name bigip
2021/08/05 08:42:36 [DEBUG] [CCCL] ConfigWriter (0xc000570b70) successfully wrote section (bigip)
2021/08/05 08:42:36 [INFO] Started config driver sub-process at pid: 14
2021/08/05 08:42:36 [INFO] [INIT] Creating Agent for as3
2021/08/05 08:42:36 [DEBUG] [INIT] Invalid trusted-certs-cfgmap option provided.
2021/08/05 08:42:36 [DEBUG] [CORE] Agent Response Worker started and blocked on channel  0xc000337080

2021/08/05 08:42:36 [INFO] [AS3] Initializing AS3 Agent
2021/08/05 08:42:36 [DEBUG] [AS3] No certs appended, using only system certs
2021/08/05 08:42:36 [DEBUG] [AS3] Validating AS3 schema with  as3-schema-3.28.0-3-cis.json
2021/08/05 08:42:36 [DEBUG] [AS3] posting GET BIGIP AS3 Version request on https://10.145.79.202/mgmt/shared/appsvcs/info

2021/08/05 08:42:36 [ERROR] [AS3] AS3 RPM is not installed on BIGIP, Error response from BIGIP with status code 404


2021/08/05 08:42:36 [CRITICAL] [INIT] Failed to initialize as3 agent, AS3 RPM is not installed on BIGIP, Error response from BIGIP with status code 404
```

**Comment by trinaths** [comment] 2021-08-09 07:11
Closing this issue.

**Closed by trinaths** 2021-08-09 07:11 UTC
Labels: awaiting response
