### ISSUE TITLE
Can not delete one ingress pool 

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#1417] opened 2020-07-23 11:33 UTC
#### Setup Details
 CIS Version : 2.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 14.0.1    
 AS3 Version: 3.x      
 Agent Mode: AS3/   
 Orchestration: K8S    
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  
Batch delete ingress object failed, the Ingress object be deleted from K8S, but the reference policy and pool can never get deleted with the following error

~~~
2020/07/22 23:24:07 [ERROR] [AS3] Big-IP Responded with code: 422
2020/07/22 23:24:07 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/k8s_AS3/Shared/Ingress_192_168_5_3_80/rules/183/actions/0/select/pool/use: contains path to non-existent object ingress_perftest299_app_svc] message:declaration is invalid] 
~~~

#### Steps To Reproduce

1) Get Code
~~~
git clone https://github.com/kylinsoong/container-ingress.git
cd container-ingress/performance/discover
~~~

2) Assume the AS3 plugin, F5 VE, network set up correctly

3) Deploy CIS POD (If CIS POD already deployed , skip this steps)
~~~
kubectl apply -f cis.yaml
~~~ 

4) Create another 5 apps and 5 ingresses
~~~
kubectl apply-f 5-ns-deploy.yaml
kubectl apply -f 5-ns-ingress.yaml 
~~~

5) check the ingress deploy successed(there should be total 5 pools)
~~~
# tmsh list ltm pool /k8s_AS3/Shared/* | grep pool | wc -l
5
~~~

6) delete one ingress
~~~
kubectl delete ingress cafe-ingress -n perftest104
~~~

7) The deletion failed, the ingress vs's policy and pool never get deleted and bigip-ctlr pod throw the below error
~~~
2020/07/23 14:15:07 [ERROR] [AS3] Big-IP Responded with code: 422
2020/07/23 14:15:07 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/k8s_AS3/Shared/Ingress_192_168_5_3_80/rules/1/actions/0/select/pool/use: contains path to non-existent object ingress_perftest100_app_svc] message:declaration is invalid]
~~~

**Comment by cisbotctlr** [comment] 2020-07-23 11:33
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by myf5** [comment] 2020-07-24 12:10
Seem like the CIS read wrong rule number, the rule does not point to the pool name.

**Comment by mdditt2000** [comment] 2020-07-27 21:40
@nandakishorepeddi @vklohiya can you try reproduce this with CIS 2.1

**Comment by mdditt2000** [comment] 2020-07-30 06:17
duplicate of https://github.com/F5Networks/k8s-bigip-ctlr/issues/1396

**Comment by trinaths** [comment] 2021-07-09 13:49
@kylinsoong  There is an issue with service labels. I tried using the above YAMLs and removed unwanted labels in services. Delete of Ingress is successful. 
Remove L36, L37 and L38 for all the services in https://github.com/kylinsoong/container-ingress/blob/master/performance/discover/5-ns-deploy.yaml#L36 and retry.  Those labels are intended for AS3 ConfigMap Services. Closing this issue.

**Closed by trinaths** 2021-07-09 13:49 UTC
Labels: In Review, ingress, recreate required
