### ISSUE TITLE
RFE: Support for Route-Domain override in F5 IPAM-integrated CR

### ISSUE THREAD

**Issue by adityoari** [F5Networks/k8s-bigip-ctlr#3418] opened 2024-05-15 11:41 UTC
#### Title
Support for Route-Domain override in F5 IPAM-integrated CR

#### Description
Enhance F5 CRs (VirtualServers, TransporServer) to expose and accept explicit Route-Domain ID

#### Actual Problem
Customer needs to override the default partition RD for the VS created by CIS due to network constraints.
With explicit addressing, they can append the %RD into `virtualServerAddresses` parameter value. 
However, with F5 IPAM Controller integration using the `ipamLabel` parameter, there's no way to configure the %RD suffix.
Trying to manually append the %RD in the IPAM spec triggers validation error, and I don't suppose external IPAM providers even understands the %RD notation.

#### Solution Proposed
Expose, accept, and implement new parameter (e.g. `ipamRD`) in the CR spec to provide Route-Domain ID to be appended to the resulting AS3 declaration.
Sample:
```yaml
spec:
  virtualServerName: "vs1"
  ipamLabel: Prod
  ipamRD: 10
  virtualServerPort: 80
```

#### Alternatives
An alternative would be to expose similar parameter in the `containers.args` of `f5-ipam-controller`, but this might completely change the format of the IP address returned by IPAM to CIS, resulting in changes in both IPAM & CIS.
Sample:
```yaml
containers:
- args:
  - --orchestration=kubernetes
  - --ip-range='{"Dev":"10.0.0.40-10.0.0.49", "Prod":"10.0.0.100-10.0.0.109"}'
  - --route-domain=10
```

#### Additional context
Due to network environment constraints, customer requires VS to be in the different RD than the partition default RD used by the Pool Members. 
See Issue #3416

**Comment by trinaths** [comment] 2024-05-21 17:31
@adityoari is https://github.com/F5Networks/k8s-bigip-ctlr/issues/3416 not duplicate of this issue ?

**Comment by trinaths** [comment] 2024-05-24 02:33
Created [CONTCNTR-4746] for internal tracking.

**Comment by vidyasagar-m** [comment] 2024-08-13 11:49
@adityoari could you confirm in which mode you need this feature?
Currently, We developed it for the Nodeport mode. For cluster mode, we need to make the changes at the Architecture level.

**Comment by mdditt2000** [comment] 2024-09-05 18:45
Resolved in CIS 2.18 - https://clouddocs.f5.com/containers/latest/reference/release-notes.html

**Closed** 2024-09-05 18:46 UTC
Labels: feature-request, JIRA
