### ISSUE TITLE
We have a ssl redirect issue when applying 2 ingresses.

### ISSUE THREAD

**Issue by type954** [F5Networks/k8s-bigip-ctlr#1456] opened 2020-08-11 10:15 UTC
#### Setup Details
 CIS Version : 2.0      
 Build: f5networks/k8s-bigip-ctlr:2.0.0       
 BIGIP Version: Big IP 15.1.0.4      
 AS3 Version: -      
 Agent Mode: CCCL       
 Orchestration: K8S      
 Orchestration Version: 1.17.6       
 Pool Mode: Cluster      
 Additional Setup details: -

#### Description  
When ssl-redirect is set using the following ingress annotation, the second ssl-redirect ingress is not applied normally with an error message.
    ingress.kubernetes.io/allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"

#### Steps To Reproduce
1) tls-ing1
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    virtual-server.f5.com/health: |
      [
        {
          "path":     "test.gcom.com/",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  10
        }
      ]
    virtual-server.f5.com/ip: 172.31.0.198
    virtual-server.f5.com/partition: k8s
    virtual-server.f5.com/serverssl: /Common/serverssl
  name: ingtest1
  namespace: default
spec:
  rules:
  - host: test.gcom.com
    http:
      paths:
      - backend:
          serviceName: nginxservice
          servicePort: 8080
        path: /
  tls:
  - secretName: /Common/clientssl
```
2) tls-ing2
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    virtual-server.f5.com/health: |
      [
        {
          "path":     "test2.gcom.com/",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  10
        }
      ]
    virtual-server.f5.com/ip: 172.31.0.199
    virtual-server.f5.com/partition: k8s
  name: ingtest2
  namespace: default
spec:
  rules:
  - host: test2.gcom.com
    http:
      paths:
      - backend:
          serviceName: nginxservice
          servicePort: 8080
        path: /
  tls:
  - secretName: /Common/clientssl
```
#### Expected Result 
Create two ssl redirect services.

#### Actual Result  
The following error occurs, and the second ingress does not work normally.

#### Diagnostic Information
Regarding Service Request #1-6568134036 |  | kubernetes bigip-ctlr 2.0, ssl-redirect error message
```
2020/08/05 07:55:28 [INFO] [2020-08-05 07:55:28,202 f5_cccl.resource.resource INFO] Updating ApiInternalDataGroup: /k8s-dev/https_redirect_dg
2020/08/05 07:55:28 [INFO] Text: '{"code":400,"message":"0107074b:3: Unable to change data group (/k8s-dev/https_redirect_dg) type. Must remove existing entries first.","errorStack":[],"apiError":3}'
2020/08/05 07:55:28 [ERROR] [2020-08-05 07:55:28,291 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiInternalDataGroup) /k8s-dev/https_redirect_dg.
2020/08/05 07:55:28 [ERROR] [2020-08-05 07:55:28,291 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.10.202.13:443/mgmt/tm/ltm/data-group/internal/~k8s-dev~https_redirect_dg/
2020/08/05 07:55:28 [ERROR] [2020-08-05 07:55:28,291 f5_cccl.service.manager ERROR] Resource /k8s-dev/https_redirect_dg update error, requeuing task...
2020/08/05 07:55:28 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:taco-registry-app ServicePort:8080 Namespace:cicd} and resource ingress_175-113-150-28_80
2020/08/05 07:55:30 [INFO] [CCCL] Wrote 5 Virtual Server and 0 IApp configs
```
#### Observations (if any)
The F5 TAC says:
The second ingress's redirection won't be working as expected. and data group for second ingress is not able to create.
bigip-ctlr pod logs will appear like below:

```
2020/08/11 01:57:49 [ERROR] [2020-08-11 01:57:49,565 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://20.20.20.48:443/mgmt/tm/ltm/data-group/internal/~k8s-service~https_redirect_dg/                <=======================
...
2020/08/11 01:57:49 [INFO] Text: '{"code":400,"message":"0107074b:3: Unable to change data group (/k8s-service/https_redirect_dg) type.  Must remove existing entries first.","errorStack":[],"apiError":3}'                                                  <=============================
```
Based on my test result, the issue because second ingress is also trying to create a data group with the same name which is https_redirect_dg.
That's why it's occurring the issue.

I posted a post 4 days ago, but no one answered.
Is there any other way to write?

**Comment by trinaths** [comment] 2021-07-09 12:57
unable to reproduce this issue in CCCL agent mode. However, with AS3 Agent mode, Ingress works well. Suggest @type954 to use AS3 as agent mode. Please share your findings.

**Comment by trinaths** [comment] 2021-07-09 13:18
Closing this issue.

**Closed by trinaths** 2021-07-09 13:18 UTC
Labels: In Review, bug
